package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityZone;
import com.consistent.ucwrt.service.EntityZoneLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityZone service. Represents a row in the &quot;Zone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityZoneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityZoneImpl
 * @see com.consistent.ucwrt.model.EntityZone
 * @generated
 */
public abstract class EntityZoneBaseImpl extends EntityZoneModelImpl
    implements EntityZone {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity zone model instance should use the {@link EntityZone} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityZoneLocalServiceUtil.addEntityZone(this);
        } else {
            EntityZoneLocalServiceUtil.updateEntityZone(this);
        }
    }
}
