package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityState;
import com.consistent.ucwrt.service.EntityStateLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityState service. Represents a row in the &quot;State&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityStateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityStateImpl
 * @see com.consistent.ucwrt.model.EntityState
 * @generated
 */
public abstract class EntityStateBaseImpl extends EntityStateModelImpl
    implements EntityState {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity state model instance should use the {@link EntityState} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityStateLocalServiceUtil.addEntityState(this);
        } else {
            EntityStateLocalServiceUtil.updateEntityState(this);
        }
    }
}
