package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityInventoryClasification;
import com.consistent.ucwrt.service.EntityInventoryClasificationLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityInventoryClasification service. Represents a row in the &quot;InventoryClasification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityInventoryClasificationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityInventoryClasificationImpl
 * @see com.consistent.ucwrt.model.EntityInventoryClasification
 * @generated
 */
public abstract class EntityInventoryClasificationBaseImpl
    extends EntityInventoryClasificationModelImpl
    implements EntityInventoryClasification {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity inventory clasification model instance should use the {@link EntityInventoryClasification} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityInventoryClasificationLocalServiceUtil.addEntityInventoryClasification(this);
        } else {
            EntityInventoryClasificationLocalServiceUtil.updateEntityInventoryClasification(this);
        }
    }
}
