package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityEmployment;
import com.consistent.ucwrt.service.EntityEmploymentLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityEmployment service. Represents a row in the &quot;Employment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityEmploymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityEmploymentImpl
 * @see com.consistent.ucwrt.model.EntityEmployment
 * @generated
 */
public abstract class EntityEmploymentBaseImpl extends EntityEmploymentModelImpl
    implements EntityEmployment {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity employment model instance should use the {@link EntityEmployment} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityEmploymentLocalServiceUtil.addEntityEmployment(this);
        } else {
            EntityEmploymentLocalServiceUtil.updateEntityEmployment(this);
        }
    }
}
