package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityBrand;
import com.consistent.ucwrt.service.EntityBrandLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityBrand service. Represents a row in the &quot;Brand&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityBrandImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityBrandImpl
 * @see com.consistent.ucwrt.model.EntityBrand
 * @generated
 */
public abstract class EntityBrandBaseImpl extends EntityBrandModelImpl
    implements EntityBrand {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity brand model instance should use the {@link EntityBrand} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityBrandLocalServiceUtil.addEntityBrand(this);
        } else {
            EntityBrandLocalServiceUtil.updateEntityBrand(this);
        }
    }
}
