package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntitySourceOfSupply;
import com.consistent.ucwrt.model.EntitySourceOfSupplyModel;
import com.consistent.ucwrt.model.EntitySourceOfSupplySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EntitySourceOfSupply service. Represents a row in the &quot;SourceOfSupply&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.consistent.ucwrt.model.EntitySourceOfSupplyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntitySourceOfSupplyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntitySourceOfSupplyImpl
 * @see com.consistent.ucwrt.model.EntitySourceOfSupply
 * @see com.consistent.ucwrt.model.EntitySourceOfSupplyModel
 * @generated
 */
@JSON(strict = true)
public class EntitySourceOfSupplyModelImpl extends BaseModelImpl<EntitySourceOfSupply>
    implements EntitySourceOfSupplyModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity source of supply model instance should use the {@link com.consistent.ucwrt.model.EntitySourceOfSupply} interface instead.
     */
    public static final String TABLE_NAME = "SourceOfSupply";
    public static final Object[][] TABLE_COLUMNS = {
            { "sourceSupplyId", Types.INTEGER },
            { "sourceOfSupply", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table SourceOfSupply (sourceSupplyId INTEGER not null primary key,sourceOfSupply VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table SourceOfSupply";
    public static final String ORDER_BY_JPQL = " ORDER BY entitySourceOfSupply.sourceSupplyId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY SourceOfSupply.sourceSupplyId ASC";
    public static final String DATA_SOURCE = "ucwrtDataSource";
    public static final String SESSION_FACTORY = "ucwrtSessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.consistent.ucwrt.model.EntitySourceOfSupply"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.consistent.ucwrt.model.EntitySourceOfSupply"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.consistent.ucwrt.model.EntitySourceOfSupply"));
    private static ClassLoader _classLoader = EntitySourceOfSupply.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            EntitySourceOfSupply.class
        };
    private int _sourceSupplyId;
    private String _sourceOfSupply;
    private EntitySourceOfSupply _escapedModel;

    public EntitySourceOfSupplyModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static EntitySourceOfSupply toModel(
        EntitySourceOfSupplySoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        EntitySourceOfSupply model = new EntitySourceOfSupplyImpl();

        model.setSourceSupplyId(soapModel.getSourceSupplyId());
        model.setSourceOfSupply(soapModel.getSourceOfSupply());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<EntitySourceOfSupply> toModels(
        EntitySourceOfSupplySoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<EntitySourceOfSupply> models = new ArrayList<EntitySourceOfSupply>(soapModels.length);

        for (EntitySourceOfSupplySoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public int getPrimaryKey() {
        return _sourceSupplyId;
    }

    @Override
    public void setPrimaryKey(int primaryKey) {
        setSourceSupplyId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _sourceSupplyId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Integer) primaryKeyObj).intValue());
    }

    @Override
    public Class<?> getModelClass() {
        return EntitySourceOfSupply.class;
    }

    @Override
    public String getModelClassName() {
        return EntitySourceOfSupply.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("sourceSupplyId", getSourceSupplyId());
        attributes.put("sourceOfSupply", getSourceOfSupply());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Integer sourceSupplyId = (Integer) attributes.get("sourceSupplyId");

        if (sourceSupplyId != null) {
            setSourceSupplyId(sourceSupplyId);
        }

        String sourceOfSupply = (String) attributes.get("sourceOfSupply");

        if (sourceOfSupply != null) {
            setSourceOfSupply(sourceOfSupply);
        }
    }

    @JSON
    @Override
    public int getSourceSupplyId() {
        return _sourceSupplyId;
    }

    @Override
    public void setSourceSupplyId(int sourceSupplyId) {
        _sourceSupplyId = sourceSupplyId;
    }

    @JSON
    @Override
    public String getSourceOfSupply() {
        if (_sourceOfSupply == null) {
            return StringPool.BLANK;
        } else {
            return _sourceOfSupply;
        }
    }

    @Override
    public void setSourceOfSupply(String sourceOfSupply) {
        _sourceOfSupply = sourceOfSupply;
    }

    @Override
    public EntitySourceOfSupply toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (EntitySourceOfSupply) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        EntitySourceOfSupplyImpl entitySourceOfSupplyImpl = new EntitySourceOfSupplyImpl();

        entitySourceOfSupplyImpl.setSourceSupplyId(getSourceSupplyId());
        entitySourceOfSupplyImpl.setSourceOfSupply(getSourceOfSupply());

        entitySourceOfSupplyImpl.resetOriginalValues();

        return entitySourceOfSupplyImpl;
    }

    @Override
    public int compareTo(EntitySourceOfSupply entitySourceOfSupply) {
        int primaryKey = entitySourceOfSupply.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof EntitySourceOfSupply)) {
            return false;
        }

        EntitySourceOfSupply entitySourceOfSupply = (EntitySourceOfSupply) obj;

        int primaryKey = entitySourceOfSupply.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<EntitySourceOfSupply> toCacheModel() {
        EntitySourceOfSupplyCacheModel entitySourceOfSupplyCacheModel = new EntitySourceOfSupplyCacheModel();

        entitySourceOfSupplyCacheModel.sourceSupplyId = getSourceSupplyId();

        entitySourceOfSupplyCacheModel.sourceOfSupply = getSourceOfSupply();

        String sourceOfSupply = entitySourceOfSupplyCacheModel.sourceOfSupply;

        if ((sourceOfSupply != null) && (sourceOfSupply.length() == 0)) {
            entitySourceOfSupplyCacheModel.sourceOfSupply = null;
        }

        return entitySourceOfSupplyCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(5);

        sb.append("{sourceSupplyId=");
        sb.append(getSourceSupplyId());
        sb.append(", sourceOfSupply=");
        sb.append(getSourceOfSupply());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(10);

        sb.append("<model><model-name>");
        sb.append("com.consistent.ucwrt.model.EntitySourceOfSupply");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>sourceSupplyId</column-name><column-value><![CDATA[");
        sb.append(getSourceSupplyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>sourceOfSupply</column-name><column-value><![CDATA[");
        sb.append(getSourceOfSupply());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
