package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityYearModelClass;
import com.consistent.ucwrt.service.EntityYearModelClassLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityYearModelClass service. Represents a row in the &quot;YearModelClass&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityYearModelClassImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityYearModelClassImpl
 * @see com.consistent.ucwrt.model.EntityYearModelClass
 * @generated
 */
public abstract class EntityYearModelClassBaseImpl
    extends EntityYearModelClassModelImpl implements EntityYearModelClass {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity year model class model instance should use the {@link EntityYearModelClass} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityYearModelClassLocalServiceUtil.addEntityYearModelClass(this);
        } else {
            EntityYearModelClassLocalServiceUtil.updateEntityYearModelClass(this);
        }
    }
}
