package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntitySale;
import com.consistent.ucwrt.service.EntitySaleLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntitySale service. Represents a row in the &quot;Sale&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntitySaleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntitySaleImpl
 * @see com.consistent.ucwrt.model.EntitySale
 * @generated
 */
public abstract class EntitySaleBaseImpl extends EntitySaleModelImpl
    implements EntitySale {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity sale model instance should use the {@link EntitySale} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntitySaleLocalServiceUtil.addEntitySale(this);
        } else {
            EntitySaleLocalServiceUtil.updateEntitySale(this);
        }
    }
}
