package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityClass;
import com.consistent.ucwrt.service.EntityClassLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityClass service. Represents a row in the &quot;Class&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityClassImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityClassImpl
 * @see com.consistent.ucwrt.model.EntityClass
 * @generated
 */
public abstract class EntityClassBaseImpl extends EntityClassModelImpl
    implements EntityClass {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity class model instance should use the {@link EntityClass} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityClassLocalServiceUtil.addEntityClass(this);
        } else {
            EntityClassLocalServiceUtil.updateEntityClass(this);
        }
    }
}
