package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityInventory;
import com.consistent.ucwrt.service.EntityInventoryLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityInventory service. Represents a row in the &quot;Inventory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityInventoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityInventoryImpl
 * @see com.consistent.ucwrt.model.EntityInventory
 * @generated
 */
public abstract class EntityInventoryBaseImpl extends EntityInventoryModelImpl
    implements EntityInventory {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity inventory model instance should use the {@link EntityInventory} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityInventoryLocalServiceUtil.addEntityInventory(this);
        } else {
            EntityInventoryLocalServiceUtil.updateEntityInventory(this);
        }
    }
}
