package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityDepartment;
import com.consistent.ucwrt.service.EntityDepartmentLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityDepartment service. Represents a row in the &quot;Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityDepartmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityDepartmentImpl
 * @see com.consistent.ucwrt.model.EntityDepartment
 * @generated
 */
public abstract class EntityDepartmentBaseImpl extends EntityDepartmentModelImpl
    implements EntityDepartment {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity department model instance should use the {@link EntityDepartment} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityDepartmentLocalServiceUtil.addEntityDepartment(this);
        } else {
            EntityDepartmentLocalServiceUtil.updateEntityDepartment(this);
        }
    }
}
