package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntitySalesPlace;
import com.consistent.ucwrt.service.EntitySalesPlaceLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntitySalesPlace service. Represents a row in the &quot;SalesPlace&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntitySalesPlaceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntitySalesPlaceImpl
 * @see com.consistent.ucwrt.model.EntitySalesPlace
 * @generated
 */
public abstract class EntitySalesPlaceBaseImpl extends EntitySalesPlaceModelImpl
    implements EntitySalesPlace {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity sales place model instance should use the {@link EntitySalesPlace} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntitySalesPlaceLocalServiceUtil.addEntitySalesPlace(this);
        } else {
            EntitySalesPlaceLocalServiceUtil.updateEntitySalesPlace(this);
        }
    }
}
