package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityMonthlySalesGoal;
import com.consistent.ucwrt.service.EntityMonthlySalesGoalLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityMonthlySalesGoal service. Represents a row in the &quot;MonthlySalesGoal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityMonthlySalesGoalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityMonthlySalesGoalImpl
 * @see com.consistent.ucwrt.model.EntityMonthlySalesGoal
 * @generated
 */
public abstract class EntityMonthlySalesGoalBaseImpl
    extends EntityMonthlySalesGoalModelImpl implements EntityMonthlySalesGoal {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity monthly sales goal model instance should use the {@link EntityMonthlySalesGoal} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityMonthlySalesGoalLocalServiceUtil.addEntityMonthlySalesGoal(this);
        } else {
            EntityMonthlySalesGoalLocalServiceUtil.updateEntityMonthlySalesGoal(this);
        }
    }
}
