package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityModel;
import com.consistent.ucwrt.service.EntityModelLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityModel service. Represents a row in the &quot;Model&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityModelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityModelImpl
 * @see com.consistent.ucwrt.model.EntityModel
 * @generated
 */
public abstract class EntityModelBaseImpl extends EntityModelModelImpl
    implements EntityModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity model model instance should use the {@link EntityModel} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityModelLocalServiceUtil.addEntityModel(this);
        } else {
            EntityModelLocalServiceUtil.updateEntityModel(this);
        }
    }
}
