package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityBusinessBrand;
import com.consistent.ucwrt.service.EntityBusinessBrandLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityBusinessBrand service. Represents a row in the &quot;BusinessBrand&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityBusinessBrandImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityBusinessBrandImpl
 * @see com.consistent.ucwrt.model.EntityBusinessBrand
 * @generated
 */
public abstract class EntityBusinessBrandBaseImpl
    extends EntityBusinessBrandModelImpl implements EntityBusinessBrand {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity business brand model instance should use the {@link EntityBusinessBrand} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityBusinessBrandLocalServiceUtil.addEntityBusinessBrand(this);
        } else {
            EntityBusinessBrandLocalServiceUtil.updateEntityBusinessBrand(this);
        }
    }
}
