package com.consistent.ucwrt.model.impl;

import com.consistent.ucwrt.model.EntityGParameter;
import com.consistent.ucwrt.service.EntityGParameterLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EntityGParameter service. Represents a row in the &quot;GParameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EntityGParameterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityGParameterImpl
 * @see com.consistent.ucwrt.model.EntityGParameter
 * @generated
 */
public abstract class EntityGParameterBaseImpl extends EntityGParameterModelImpl
    implements EntityGParameter {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a entity g parameter model instance should use the {@link EntityGParameter} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EntityGParameterLocalServiceUtil.addEntityGParameter(this);
        } else {
            EntityGParameterLocalServiceUtil.updateEntityGParameter(this);
        }
    }
}
