package com.consistent.ucwrt.service.base;

import com.consistent.ucwrt.model.EntityEvent;
import com.consistent.ucwrt.service.EntityEventLocalService;
import com.consistent.ucwrt.service.persistence.EntityAddressPersistence;
import com.consistent.ucwrt.service.persistence.EntityBrandPersistence;
import com.consistent.ucwrt.service.persistence.EntityBusinessBrandPersistence;
import com.consistent.ucwrt.service.persistence.EntityClassPersistence;
import com.consistent.ucwrt.service.persistence.EntityCustomerPersistence;
import com.consistent.ucwrt.service.persistence.EntityDealerPersistence;
import com.consistent.ucwrt.service.persistence.EntityDepartmentPersistence;
import com.consistent.ucwrt.service.persistence.EntityEmployeesPersistence;
import com.consistent.ucwrt.service.persistence.EntityEmploymentPersistence;
import com.consistent.ucwrt.service.persistence.EntityEquipmentPersistence;
import com.consistent.ucwrt.service.persistence.EntityEventPersistence;
import com.consistent.ucwrt.service.persistence.EntityGParameterPersistence;
import com.consistent.ucwrt.service.persistence.EntityIntervalosPersistence;
import com.consistent.ucwrt.service.persistence.EntityInventoryClasificationPersistence;
import com.consistent.ucwrt.service.persistence.EntityInventoryPersistence;
import com.consistent.ucwrt.service.persistence.EntityModelPersistence;
import com.consistent.ucwrt.service.persistence.EntityMonthlySalesGoalPersistence;
import com.consistent.ucwrt.service.persistence.EntityMunicipalityPersistence;
import com.consistent.ucwrt.service.persistence.EntityProspectionPersistence;
import com.consistent.ucwrt.service.persistence.EntitySalePersistence;
import com.consistent.ucwrt.service.persistence.EntitySalesPlacePersistence;
import com.consistent.ucwrt.service.persistence.EntitySourceOfSupplyPersistence;
import com.consistent.ucwrt.service.persistence.EntityStatePersistence;
import com.consistent.ucwrt.service.persistence.EntityStatusPersistence;
import com.consistent.ucwrt.service.persistence.EntitySuburbPersistence;
import com.consistent.ucwrt.service.persistence.EntityVersionAutoPersistence;
import com.consistent.ucwrt.service.persistence.EntityVersionEquipmentPersistence;
import com.consistent.ucwrt.service.persistence.EntityWayToPayPersistence;
import com.consistent.ucwrt.service.persistence.EntityYearModelClassPersistence;
import com.consistent.ucwrt.service.persistence.EntityYearModelPersistence;
import com.consistent.ucwrt.service.persistence.EntityZonePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the entity event local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.consistent.ucwrt.service.impl.EntityEventLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.consistent.ucwrt.service.impl.EntityEventLocalServiceImpl
 * @see com.consistent.ucwrt.service.EntityEventLocalServiceUtil
 * @generated
 */
public abstract class EntityEventLocalServiceBaseImpl
    extends BaseLocalServiceImpl implements EntityEventLocalService,
        IdentifiableBean {
    @BeanReference(type = com.consistent.ucwrt.service.EntityAddressLocalService.class)
    protected com.consistent.ucwrt.service.EntityAddressLocalService entityAddressLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityAddressService.class)
    protected com.consistent.ucwrt.service.EntityAddressService entityAddressService;
    @BeanReference(type = EntityAddressPersistence.class)
    protected EntityAddressPersistence entityAddressPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityBrandLocalService.class)
    protected com.consistent.ucwrt.service.EntityBrandLocalService entityBrandLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityBrandService.class)
    protected com.consistent.ucwrt.service.EntityBrandService entityBrandService;
    @BeanReference(type = EntityBrandPersistence.class)
    protected EntityBrandPersistence entityBrandPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityBusinessBrandLocalService.class)
    protected com.consistent.ucwrt.service.EntityBusinessBrandLocalService entityBusinessBrandLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityBusinessBrandService.class)
    protected com.consistent.ucwrt.service.EntityBusinessBrandService entityBusinessBrandService;
    @BeanReference(type = EntityBusinessBrandPersistence.class)
    protected EntityBusinessBrandPersistence entityBusinessBrandPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityClassLocalService.class)
    protected com.consistent.ucwrt.service.EntityClassLocalService entityClassLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityClassService.class)
    protected com.consistent.ucwrt.service.EntityClassService entityClassService;
    @BeanReference(type = EntityClassPersistence.class)
    protected EntityClassPersistence entityClassPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityCustomerLocalService.class)
    protected com.consistent.ucwrt.service.EntityCustomerLocalService entityCustomerLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityCustomerService.class)
    protected com.consistent.ucwrt.service.EntityCustomerService entityCustomerService;
    @BeanReference(type = EntityCustomerPersistence.class)
    protected EntityCustomerPersistence entityCustomerPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityDealerLocalService.class)
    protected com.consistent.ucwrt.service.EntityDealerLocalService entityDealerLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityDealerService.class)
    protected com.consistent.ucwrt.service.EntityDealerService entityDealerService;
    @BeanReference(type = EntityDealerPersistence.class)
    protected EntityDealerPersistence entityDealerPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityDepartmentLocalService.class)
    protected com.consistent.ucwrt.service.EntityDepartmentLocalService entityDepartmentLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityDepartmentService.class)
    protected com.consistent.ucwrt.service.EntityDepartmentService entityDepartmentService;
    @BeanReference(type = EntityDepartmentPersistence.class)
    protected EntityDepartmentPersistence entityDepartmentPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityEmployeesLocalService.class)
    protected com.consistent.ucwrt.service.EntityEmployeesLocalService entityEmployeesLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityEmployeesService.class)
    protected com.consistent.ucwrt.service.EntityEmployeesService entityEmployeesService;
    @BeanReference(type = EntityEmployeesPersistence.class)
    protected EntityEmployeesPersistence entityEmployeesPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityEmploymentLocalService.class)
    protected com.consistent.ucwrt.service.EntityEmploymentLocalService entityEmploymentLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityEmploymentService.class)
    protected com.consistent.ucwrt.service.EntityEmploymentService entityEmploymentService;
    @BeanReference(type = EntityEmploymentPersistence.class)
    protected EntityEmploymentPersistence entityEmploymentPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityEquipmentLocalService.class)
    protected com.consistent.ucwrt.service.EntityEquipmentLocalService entityEquipmentLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityEquipmentService.class)
    protected com.consistent.ucwrt.service.EntityEquipmentService entityEquipmentService;
    @BeanReference(type = EntityEquipmentPersistence.class)
    protected EntityEquipmentPersistence entityEquipmentPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityEventLocalService.class)
    protected com.consistent.ucwrt.service.EntityEventLocalService entityEventLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityEventService.class)
    protected com.consistent.ucwrt.service.EntityEventService entityEventService;
    @BeanReference(type = EntityEventPersistence.class)
    protected EntityEventPersistence entityEventPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityGParameterLocalService.class)
    protected com.consistent.ucwrt.service.EntityGParameterLocalService entityGParameterLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityGParameterService.class)
    protected com.consistent.ucwrt.service.EntityGParameterService entityGParameterService;
    @BeanReference(type = EntityGParameterPersistence.class)
    protected EntityGParameterPersistence entityGParameterPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityIntervalosLocalService.class)
    protected com.consistent.ucwrt.service.EntityIntervalosLocalService entityIntervalosLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityIntervalosService.class)
    protected com.consistent.ucwrt.service.EntityIntervalosService entityIntervalosService;
    @BeanReference(type = EntityIntervalosPersistence.class)
    protected EntityIntervalosPersistence entityIntervalosPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityInventoryLocalService.class)
    protected com.consistent.ucwrt.service.EntityInventoryLocalService entityInventoryLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityInventoryService.class)
    protected com.consistent.ucwrt.service.EntityInventoryService entityInventoryService;
    @BeanReference(type = EntityInventoryPersistence.class)
    protected EntityInventoryPersistence entityInventoryPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityInventoryClasificationLocalService.class)
    protected com.consistent.ucwrt.service.EntityInventoryClasificationLocalService entityInventoryClasificationLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityInventoryClasificationService.class)
    protected com.consistent.ucwrt.service.EntityInventoryClasificationService entityInventoryClasificationService;
    @BeanReference(type = EntityInventoryClasificationPersistence.class)
    protected EntityInventoryClasificationPersistence entityInventoryClasificationPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityModelLocalService.class)
    protected com.consistent.ucwrt.service.EntityModelLocalService entityModelLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityModelService.class)
    protected com.consistent.ucwrt.service.EntityModelService entityModelService;
    @BeanReference(type = EntityModelPersistence.class)
    protected EntityModelPersistence entityModelPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityMonthlySalesGoalLocalService.class)
    protected com.consistent.ucwrt.service.EntityMonthlySalesGoalLocalService entityMonthlySalesGoalLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityMonthlySalesGoalService.class)
    protected com.consistent.ucwrt.service.EntityMonthlySalesGoalService entityMonthlySalesGoalService;
    @BeanReference(type = EntityMonthlySalesGoalPersistence.class)
    protected EntityMonthlySalesGoalPersistence entityMonthlySalesGoalPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityMunicipalityLocalService.class)
    protected com.consistent.ucwrt.service.EntityMunicipalityLocalService entityMunicipalityLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityMunicipalityService.class)
    protected com.consistent.ucwrt.service.EntityMunicipalityService entityMunicipalityService;
    @BeanReference(type = EntityMunicipalityPersistence.class)
    protected EntityMunicipalityPersistence entityMunicipalityPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityProspectionLocalService.class)
    protected com.consistent.ucwrt.service.EntityProspectionLocalService entityProspectionLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityProspectionService.class)
    protected com.consistent.ucwrt.service.EntityProspectionService entityProspectionService;
    @BeanReference(type = EntityProspectionPersistence.class)
    protected EntityProspectionPersistence entityProspectionPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntitySaleLocalService.class)
    protected com.consistent.ucwrt.service.EntitySaleLocalService entitySaleLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntitySaleService.class)
    protected com.consistent.ucwrt.service.EntitySaleService entitySaleService;
    @BeanReference(type = EntitySalePersistence.class)
    protected EntitySalePersistence entitySalePersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntitySalesPlaceLocalService.class)
    protected com.consistent.ucwrt.service.EntitySalesPlaceLocalService entitySalesPlaceLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntitySalesPlaceService.class)
    protected com.consistent.ucwrt.service.EntitySalesPlaceService entitySalesPlaceService;
    @BeanReference(type = EntitySalesPlacePersistence.class)
    protected EntitySalesPlacePersistence entitySalesPlacePersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntitySourceOfSupplyLocalService.class)
    protected com.consistent.ucwrt.service.EntitySourceOfSupplyLocalService entitySourceOfSupplyLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntitySourceOfSupplyService.class)
    protected com.consistent.ucwrt.service.EntitySourceOfSupplyService entitySourceOfSupplyService;
    @BeanReference(type = EntitySourceOfSupplyPersistence.class)
    protected EntitySourceOfSupplyPersistence entitySourceOfSupplyPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityStateLocalService.class)
    protected com.consistent.ucwrt.service.EntityStateLocalService entityStateLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityStateService.class)
    protected com.consistent.ucwrt.service.EntityStateService entityStateService;
    @BeanReference(type = EntityStatePersistence.class)
    protected EntityStatePersistence entityStatePersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityStatusLocalService.class)
    protected com.consistent.ucwrt.service.EntityStatusLocalService entityStatusLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityStatusService.class)
    protected com.consistent.ucwrt.service.EntityStatusService entityStatusService;
    @BeanReference(type = EntityStatusPersistence.class)
    protected EntityStatusPersistence entityStatusPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntitySuburbLocalService.class)
    protected com.consistent.ucwrt.service.EntitySuburbLocalService entitySuburbLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntitySuburbService.class)
    protected com.consistent.ucwrt.service.EntitySuburbService entitySuburbService;
    @BeanReference(type = EntitySuburbPersistence.class)
    protected EntitySuburbPersistence entitySuburbPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityVersionAutoLocalService.class)
    protected com.consistent.ucwrt.service.EntityVersionAutoLocalService entityVersionAutoLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityVersionAutoService.class)
    protected com.consistent.ucwrt.service.EntityVersionAutoService entityVersionAutoService;
    @BeanReference(type = EntityVersionAutoPersistence.class)
    protected EntityVersionAutoPersistence entityVersionAutoPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityVersionEquipmentLocalService.class)
    protected com.consistent.ucwrt.service.EntityVersionEquipmentLocalService entityVersionEquipmentLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityVersionEquipmentService.class)
    protected com.consistent.ucwrt.service.EntityVersionEquipmentService entityVersionEquipmentService;
    @BeanReference(type = EntityVersionEquipmentPersistence.class)
    protected EntityVersionEquipmentPersistence entityVersionEquipmentPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityWayToPayLocalService.class)
    protected com.consistent.ucwrt.service.EntityWayToPayLocalService entityWayToPayLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityWayToPayService.class)
    protected com.consistent.ucwrt.service.EntityWayToPayService entityWayToPayService;
    @BeanReference(type = EntityWayToPayPersistence.class)
    protected EntityWayToPayPersistence entityWayToPayPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityYearModelLocalService.class)
    protected com.consistent.ucwrt.service.EntityYearModelLocalService entityYearModelLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityYearModelService.class)
    protected com.consistent.ucwrt.service.EntityYearModelService entityYearModelService;
    @BeanReference(type = EntityYearModelPersistence.class)
    protected EntityYearModelPersistence entityYearModelPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityYearModelClassLocalService.class)
    protected com.consistent.ucwrt.service.EntityYearModelClassLocalService entityYearModelClassLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityYearModelClassService.class)
    protected com.consistent.ucwrt.service.EntityYearModelClassService entityYearModelClassService;
    @BeanReference(type = EntityYearModelClassPersistence.class)
    protected EntityYearModelClassPersistence entityYearModelClassPersistence;
    @BeanReference(type = com.consistent.ucwrt.service.EntityZoneLocalService.class)
    protected com.consistent.ucwrt.service.EntityZoneLocalService entityZoneLocalService;
    @BeanReference(type = com.consistent.ucwrt.service.EntityZoneService.class)
    protected com.consistent.ucwrt.service.EntityZoneService entityZoneService;
    @BeanReference(type = EntityZonePersistence.class)
    protected EntityZonePersistence entityZonePersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private EntityEventLocalServiceClpInvoker _clpInvoker = new EntityEventLocalServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.consistent.ucwrt.service.EntityEventLocalServiceUtil} to access the entity event local service.
     */

    /**
     * Adds the entity event to the database. Also notifies the appropriate model listeners.
     *
     * @param entityEvent the entity event
     * @return the entity event that was added
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public EntityEvent addEntityEvent(EntityEvent entityEvent)
        throws SystemException {
        entityEvent.setNew(true);

        return entityEventPersistence.update(entityEvent);
    }

    /**
     * Creates a new entity event with the primary key. Does not add the entity event to the database.
     *
     * @param eventId the primary key for the new entity event
     * @return the new entity event
     */
    @Override
    public EntityEvent createEntityEvent(int eventId) {
        return entityEventPersistence.create(eventId);
    }

    /**
     * Deletes the entity event with the primary key from the database. Also notifies the appropriate model listeners.
     *
     * @param eventId the primary key of the entity event
     * @return the entity event that was removed
     * @throws PortalException if a entity event with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public EntityEvent deleteEntityEvent(int eventId)
        throws PortalException, SystemException {
        return entityEventPersistence.remove(eventId);
    }

    /**
     * Deletes the entity event from the database. Also notifies the appropriate model listeners.
     *
     * @param entityEvent the entity event
     * @return the entity event that was removed
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.DELETE)
    @Override
    public EntityEvent deleteEntityEvent(EntityEvent entityEvent)
        throws SystemException {
        return entityEventPersistence.remove(entityEvent);
    }

    @Override
    public DynamicQuery dynamicQuery() {
        Class<?> clazz = getClass();

        return DynamicQueryFactoryUtil.forClass(EntityEvent.class,
            clazz.getClassLoader());
    }

    /**
     * Performs a dynamic query on the database and returns the matching rows.
     *
     * @param dynamicQuery the dynamic query
     * @return the matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery)
        throws SystemException {
        return entityEventPersistence.findWithDynamicQuery(dynamicQuery);
    }

    /**
     * Performs a dynamic query on the database and returns a range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.consistent.ucwrt.model.impl.EntityEventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @return the range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
        throws SystemException {
        return entityEventPersistence.findWithDynamicQuery(dynamicQuery, start,
            end);
    }

    /**
     * Performs a dynamic query on the database and returns an ordered range of the matching rows.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.consistent.ucwrt.model.impl.EntityEventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param dynamicQuery the dynamic query
     * @param start the lower bound of the range of model instances
     * @param end the upper bound of the range of model instances (not inclusive)
     * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
     * @return the ordered range of matching rows
     * @throws SystemException if a system exception occurred
     */
    @Override
    @SuppressWarnings("rawtypes")
    public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
        OrderByComparator orderByComparator) throws SystemException {
        return entityEventPersistence.findWithDynamicQuery(dynamicQuery, start,
            end, orderByComparator);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery)
        throws SystemException {
        return entityEventPersistence.countWithDynamicQuery(dynamicQuery);
    }

    /**
     * Returns the number of rows that match the dynamic query.
     *
     * @param dynamicQuery the dynamic query
     * @param projection the projection to apply to the query
     * @return the number of rows that match the dynamic query
     * @throws SystemException if a system exception occurred
     */
    @Override
    public long dynamicQueryCount(DynamicQuery dynamicQuery,
        Projection projection) throws SystemException {
        return entityEventPersistence.countWithDynamicQuery(dynamicQuery,
            projection);
    }

    @Override
    public EntityEvent fetchEntityEvent(int eventId) throws SystemException {
        return entityEventPersistence.fetchByPrimaryKey(eventId);
    }

    /**
     * Returns the entity event with the primary key.
     *
     * @param eventId the primary key of the entity event
     * @return the entity event
     * @throws PortalException if a entity event with the primary key could not be found
     * @throws SystemException if a system exception occurred
     */
    @Override
    public EntityEvent getEntityEvent(int eventId)
        throws PortalException, SystemException {
        return entityEventPersistence.findByPrimaryKey(eventId);
    }

    @Override
    public PersistedModel getPersistedModel(Serializable primaryKeyObj)
        throws PortalException, SystemException {
        return entityEventPersistence.findByPrimaryKey(primaryKeyObj);
    }

    /**
     * Returns a range of all the entity events.
     *
     * <p>
     * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.consistent.ucwrt.model.impl.EntityEventModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
     * </p>
     *
     * @param start the lower bound of the range of entity events
     * @param end the upper bound of the range of entity events (not inclusive)
     * @return the range of entity events
     * @throws SystemException if a system exception occurred
     */
    @Override
    public List<EntityEvent> getEntityEvents(int start, int end)
        throws SystemException {
        return entityEventPersistence.findAll(start, end);
    }

    /**
     * Returns the number of entity events.
     *
     * @return the number of entity events
     * @throws SystemException if a system exception occurred
     */
    @Override
    public int getEntityEventsCount() throws SystemException {
        return entityEventPersistence.countAll();
    }

    /**
     * Updates the entity event in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
     *
     * @param entityEvent the entity event
     * @return the entity event that was updated
     * @throws SystemException if a system exception occurred
     */
    @Indexable(type = IndexableType.REINDEX)
    @Override
    public EntityEvent updateEntityEvent(EntityEvent entityEvent)
        throws SystemException {
        return entityEventPersistence.update(entityEvent);
    }

    /**
     * Returns the entity address local service.
     *
     * @return the entity address local service
     */
    public com.consistent.ucwrt.service.EntityAddressLocalService getEntityAddressLocalService() {
        return entityAddressLocalService;
    }

    /**
     * Sets the entity address local service.
     *
     * @param entityAddressLocalService the entity address local service
     */
    public void setEntityAddressLocalService(
        com.consistent.ucwrt.service.EntityAddressLocalService entityAddressLocalService) {
        this.entityAddressLocalService = entityAddressLocalService;
    }

    /**
     * Returns the entity address remote service.
     *
     * @return the entity address remote service
     */
    public com.consistent.ucwrt.service.EntityAddressService getEntityAddressService() {
        return entityAddressService;
    }

    /**
     * Sets the entity address remote service.
     *
     * @param entityAddressService the entity address remote service
     */
    public void setEntityAddressService(
        com.consistent.ucwrt.service.EntityAddressService entityAddressService) {
        this.entityAddressService = entityAddressService;
    }

    /**
     * Returns the entity address persistence.
     *
     * @return the entity address persistence
     */
    public EntityAddressPersistence getEntityAddressPersistence() {
        return entityAddressPersistence;
    }

    /**
     * Sets the entity address persistence.
     *
     * @param entityAddressPersistence the entity address persistence
     */
    public void setEntityAddressPersistence(
        EntityAddressPersistence entityAddressPersistence) {
        this.entityAddressPersistence = entityAddressPersistence;
    }

    /**
     * Returns the entity brand local service.
     *
     * @return the entity brand local service
     */
    public com.consistent.ucwrt.service.EntityBrandLocalService getEntityBrandLocalService() {
        return entityBrandLocalService;
    }

    /**
     * Sets the entity brand local service.
     *
     * @param entityBrandLocalService the entity brand local service
     */
    public void setEntityBrandLocalService(
        com.consistent.ucwrt.service.EntityBrandLocalService entityBrandLocalService) {
        this.entityBrandLocalService = entityBrandLocalService;
    }

    /**
     * Returns the entity brand remote service.
     *
     * @return the entity brand remote service
     */
    public com.consistent.ucwrt.service.EntityBrandService getEntityBrandService() {
        return entityBrandService;
    }

    /**
     * Sets the entity brand remote service.
     *
     * @param entityBrandService the entity brand remote service
     */
    public void setEntityBrandService(
        com.consistent.ucwrt.service.EntityBrandService entityBrandService) {
        this.entityBrandService = entityBrandService;
    }

    /**
     * Returns the entity brand persistence.
     *
     * @return the entity brand persistence
     */
    public EntityBrandPersistence getEntityBrandPersistence() {
        return entityBrandPersistence;
    }

    /**
     * Sets the entity brand persistence.
     *
     * @param entityBrandPersistence the entity brand persistence
     */
    public void setEntityBrandPersistence(
        EntityBrandPersistence entityBrandPersistence) {
        this.entityBrandPersistence = entityBrandPersistence;
    }

    /**
     * Returns the entity business brand local service.
     *
     * @return the entity business brand local service
     */
    public com.consistent.ucwrt.service.EntityBusinessBrandLocalService getEntityBusinessBrandLocalService() {
        return entityBusinessBrandLocalService;
    }

    /**
     * Sets the entity business brand local service.
     *
     * @param entityBusinessBrandLocalService the entity business brand local service
     */
    public void setEntityBusinessBrandLocalService(
        com.consistent.ucwrt.service.EntityBusinessBrandLocalService entityBusinessBrandLocalService) {
        this.entityBusinessBrandLocalService = entityBusinessBrandLocalService;
    }

    /**
     * Returns the entity business brand remote service.
     *
     * @return the entity business brand remote service
     */
    public com.consistent.ucwrt.service.EntityBusinessBrandService getEntityBusinessBrandService() {
        return entityBusinessBrandService;
    }

    /**
     * Sets the entity business brand remote service.
     *
     * @param entityBusinessBrandService the entity business brand remote service
     */
    public void setEntityBusinessBrandService(
        com.consistent.ucwrt.service.EntityBusinessBrandService entityBusinessBrandService) {
        this.entityBusinessBrandService = entityBusinessBrandService;
    }

    /**
     * Returns the entity business brand persistence.
     *
     * @return the entity business brand persistence
     */
    public EntityBusinessBrandPersistence getEntityBusinessBrandPersistence() {
        return entityBusinessBrandPersistence;
    }

    /**
     * Sets the entity business brand persistence.
     *
     * @param entityBusinessBrandPersistence the entity business brand persistence
     */
    public void setEntityBusinessBrandPersistence(
        EntityBusinessBrandPersistence entityBusinessBrandPersistence) {
        this.entityBusinessBrandPersistence = entityBusinessBrandPersistence;
    }

    /**
     * Returns the entity class local service.
     *
     * @return the entity class local service
     */
    public com.consistent.ucwrt.service.EntityClassLocalService getEntityClassLocalService() {
        return entityClassLocalService;
    }

    /**
     * Sets the entity class local service.
     *
     * @param entityClassLocalService the entity class local service
     */
    public void setEntityClassLocalService(
        com.consistent.ucwrt.service.EntityClassLocalService entityClassLocalService) {
        this.entityClassLocalService = entityClassLocalService;
    }

    /**
     * Returns the entity class remote service.
     *
     * @return the entity class remote service
     */
    public com.consistent.ucwrt.service.EntityClassService getEntityClassService() {
        return entityClassService;
    }

    /**
     * Sets the entity class remote service.
     *
     * @param entityClassService the entity class remote service
     */
    public void setEntityClassService(
        com.consistent.ucwrt.service.EntityClassService entityClassService) {
        this.entityClassService = entityClassService;
    }

    /**
     * Returns the entity class persistence.
     *
     * @return the entity class persistence
     */
    public EntityClassPersistence getEntityClassPersistence() {
        return entityClassPersistence;
    }

    /**
     * Sets the entity class persistence.
     *
     * @param entityClassPersistence the entity class persistence
     */
    public void setEntityClassPersistence(
        EntityClassPersistence entityClassPersistence) {
        this.entityClassPersistence = entityClassPersistence;
    }

    /**
     * Returns the entity customer local service.
     *
     * @return the entity customer local service
     */
    public com.consistent.ucwrt.service.EntityCustomerLocalService getEntityCustomerLocalService() {
        return entityCustomerLocalService;
    }

    /**
     * Sets the entity customer local service.
     *
     * @param entityCustomerLocalService the entity customer local service
     */
    public void setEntityCustomerLocalService(
        com.consistent.ucwrt.service.EntityCustomerLocalService entityCustomerLocalService) {
        this.entityCustomerLocalService = entityCustomerLocalService;
    }

    /**
     * Returns the entity customer remote service.
     *
     * @return the entity customer remote service
     */
    public com.consistent.ucwrt.service.EntityCustomerService getEntityCustomerService() {
        return entityCustomerService;
    }

    /**
     * Sets the entity customer remote service.
     *
     * @param entityCustomerService the entity customer remote service
     */
    public void setEntityCustomerService(
        com.consistent.ucwrt.service.EntityCustomerService entityCustomerService) {
        this.entityCustomerService = entityCustomerService;
    }

    /**
     * Returns the entity customer persistence.
     *
     * @return the entity customer persistence
     */
    public EntityCustomerPersistence getEntityCustomerPersistence() {
        return entityCustomerPersistence;
    }

    /**
     * Sets the entity customer persistence.
     *
     * @param entityCustomerPersistence the entity customer persistence
     */
    public void setEntityCustomerPersistence(
        EntityCustomerPersistence entityCustomerPersistence) {
        this.entityCustomerPersistence = entityCustomerPersistence;
    }

    /**
     * Returns the entity dealer local service.
     *
     * @return the entity dealer local service
     */
    public com.consistent.ucwrt.service.EntityDealerLocalService getEntityDealerLocalService() {
        return entityDealerLocalService;
    }

    /**
     * Sets the entity dealer local service.
     *
     * @param entityDealerLocalService the entity dealer local service
     */
    public void setEntityDealerLocalService(
        com.consistent.ucwrt.service.EntityDealerLocalService entityDealerLocalService) {
        this.entityDealerLocalService = entityDealerLocalService;
    }

    /**
     * Returns the entity dealer remote service.
     *
     * @return the entity dealer remote service
     */
    public com.consistent.ucwrt.service.EntityDealerService getEntityDealerService() {
        return entityDealerService;
    }

    /**
     * Sets the entity dealer remote service.
     *
     * @param entityDealerService the entity dealer remote service
     */
    public void setEntityDealerService(
        com.consistent.ucwrt.service.EntityDealerService entityDealerService) {
        this.entityDealerService = entityDealerService;
    }

    /**
     * Returns the entity dealer persistence.
     *
     * @return the entity dealer persistence
     */
    public EntityDealerPersistence getEntityDealerPersistence() {
        return entityDealerPersistence;
    }

    /**
     * Sets the entity dealer persistence.
     *
     * @param entityDealerPersistence the entity dealer persistence
     */
    public void setEntityDealerPersistence(
        EntityDealerPersistence entityDealerPersistence) {
        this.entityDealerPersistence = entityDealerPersistence;
    }

    /**
     * Returns the entity department local service.
     *
     * @return the entity department local service
     */
    public com.consistent.ucwrt.service.EntityDepartmentLocalService getEntityDepartmentLocalService() {
        return entityDepartmentLocalService;
    }

    /**
     * Sets the entity department local service.
     *
     * @param entityDepartmentLocalService the entity department local service
     */
    public void setEntityDepartmentLocalService(
        com.consistent.ucwrt.service.EntityDepartmentLocalService entityDepartmentLocalService) {
        this.entityDepartmentLocalService = entityDepartmentLocalService;
    }

    /**
     * Returns the entity department remote service.
     *
     * @return the entity department remote service
     */
    public com.consistent.ucwrt.service.EntityDepartmentService getEntityDepartmentService() {
        return entityDepartmentService;
    }

    /**
     * Sets the entity department remote service.
     *
     * @param entityDepartmentService the entity department remote service
     */
    public void setEntityDepartmentService(
        com.consistent.ucwrt.service.EntityDepartmentService entityDepartmentService) {
        this.entityDepartmentService = entityDepartmentService;
    }

    /**
     * Returns the entity department persistence.
     *
     * @return the entity department persistence
     */
    public EntityDepartmentPersistence getEntityDepartmentPersistence() {
        return entityDepartmentPersistence;
    }

    /**
     * Sets the entity department persistence.
     *
     * @param entityDepartmentPersistence the entity department persistence
     */
    public void setEntityDepartmentPersistence(
        EntityDepartmentPersistence entityDepartmentPersistence) {
        this.entityDepartmentPersistence = entityDepartmentPersistence;
    }

    /**
     * Returns the entity employees local service.
     *
     * @return the entity employees local service
     */
    public com.consistent.ucwrt.service.EntityEmployeesLocalService getEntityEmployeesLocalService() {
        return entityEmployeesLocalService;
    }

    /**
     * Sets the entity employees local service.
     *
     * @param entityEmployeesLocalService the entity employees local service
     */
    public void setEntityEmployeesLocalService(
        com.consistent.ucwrt.service.EntityEmployeesLocalService entityEmployeesLocalService) {
        this.entityEmployeesLocalService = entityEmployeesLocalService;
    }

    /**
     * Returns the entity employees remote service.
     *
     * @return the entity employees remote service
     */
    public com.consistent.ucwrt.service.EntityEmployeesService getEntityEmployeesService() {
        return entityEmployeesService;
    }

    /**
     * Sets the entity employees remote service.
     *
     * @param entityEmployeesService the entity employees remote service
     */
    public void setEntityEmployeesService(
        com.consistent.ucwrt.service.EntityEmployeesService entityEmployeesService) {
        this.entityEmployeesService = entityEmployeesService;
    }

    /**
     * Returns the entity employees persistence.
     *
     * @return the entity employees persistence
     */
    public EntityEmployeesPersistence getEntityEmployeesPersistence() {
        return entityEmployeesPersistence;
    }

    /**
     * Sets the entity employees persistence.
     *
     * @param entityEmployeesPersistence the entity employees persistence
     */
    public void setEntityEmployeesPersistence(
        EntityEmployeesPersistence entityEmployeesPersistence) {
        this.entityEmployeesPersistence = entityEmployeesPersistence;
    }

    /**
     * Returns the entity employment local service.
     *
     * @return the entity employment local service
     */
    public com.consistent.ucwrt.service.EntityEmploymentLocalService getEntityEmploymentLocalService() {
        return entityEmploymentLocalService;
    }

    /**
     * Sets the entity employment local service.
     *
     * @param entityEmploymentLocalService the entity employment local service
     */
    public void setEntityEmploymentLocalService(
        com.consistent.ucwrt.service.EntityEmploymentLocalService entityEmploymentLocalService) {
        this.entityEmploymentLocalService = entityEmploymentLocalService;
    }

    /**
     * Returns the entity employment remote service.
     *
     * @return the entity employment remote service
     */
    public com.consistent.ucwrt.service.EntityEmploymentService getEntityEmploymentService() {
        return entityEmploymentService;
    }

    /**
     * Sets the entity employment remote service.
     *
     * @param entityEmploymentService the entity employment remote service
     */
    public void setEntityEmploymentService(
        com.consistent.ucwrt.service.EntityEmploymentService entityEmploymentService) {
        this.entityEmploymentService = entityEmploymentService;
    }

    /**
     * Returns the entity employment persistence.
     *
     * @return the entity employment persistence
     */
    public EntityEmploymentPersistence getEntityEmploymentPersistence() {
        return entityEmploymentPersistence;
    }

    /**
     * Sets the entity employment persistence.
     *
     * @param entityEmploymentPersistence the entity employment persistence
     */
    public void setEntityEmploymentPersistence(
        EntityEmploymentPersistence entityEmploymentPersistence) {
        this.entityEmploymentPersistence = entityEmploymentPersistence;
    }

    /**
     * Returns the entity equipment local service.
     *
     * @return the entity equipment local service
     */
    public com.consistent.ucwrt.service.EntityEquipmentLocalService getEntityEquipmentLocalService() {
        return entityEquipmentLocalService;
    }

    /**
     * Sets the entity equipment local service.
     *
     * @param entityEquipmentLocalService the entity equipment local service
     */
    public void setEntityEquipmentLocalService(
        com.consistent.ucwrt.service.EntityEquipmentLocalService entityEquipmentLocalService) {
        this.entityEquipmentLocalService = entityEquipmentLocalService;
    }

    /**
     * Returns the entity equipment remote service.
     *
     * @return the entity equipment remote service
     */
    public com.consistent.ucwrt.service.EntityEquipmentService getEntityEquipmentService() {
        return entityEquipmentService;
    }

    /**
     * Sets the entity equipment remote service.
     *
     * @param entityEquipmentService the entity equipment remote service
     */
    public void setEntityEquipmentService(
        com.consistent.ucwrt.service.EntityEquipmentService entityEquipmentService) {
        this.entityEquipmentService = entityEquipmentService;
    }

    /**
     * Returns the entity equipment persistence.
     *
     * @return the entity equipment persistence
     */
    public EntityEquipmentPersistence getEntityEquipmentPersistence() {
        return entityEquipmentPersistence;
    }

    /**
     * Sets the entity equipment persistence.
     *
     * @param entityEquipmentPersistence the entity equipment persistence
     */
    public void setEntityEquipmentPersistence(
        EntityEquipmentPersistence entityEquipmentPersistence) {
        this.entityEquipmentPersistence = entityEquipmentPersistence;
    }

    /**
     * Returns the entity event local service.
     *
     * @return the entity event local service
     */
    public com.consistent.ucwrt.service.EntityEventLocalService getEntityEventLocalService() {
        return entityEventLocalService;
    }

    /**
     * Sets the entity event local service.
     *
     * @param entityEventLocalService the entity event local service
     */
    public void setEntityEventLocalService(
        com.consistent.ucwrt.service.EntityEventLocalService entityEventLocalService) {
        this.entityEventLocalService = entityEventLocalService;
    }

    /**
     * Returns the entity event remote service.
     *
     * @return the entity event remote service
     */
    public com.consistent.ucwrt.service.EntityEventService getEntityEventService() {
        return entityEventService;
    }

    /**
     * Sets the entity event remote service.
     *
     * @param entityEventService the entity event remote service
     */
    public void setEntityEventService(
        com.consistent.ucwrt.service.EntityEventService entityEventService) {
        this.entityEventService = entityEventService;
    }

    /**
     * Returns the entity event persistence.
     *
     * @return the entity event persistence
     */
    public EntityEventPersistence getEntityEventPersistence() {
        return entityEventPersistence;
    }

    /**
     * Sets the entity event persistence.
     *
     * @param entityEventPersistence the entity event persistence
     */
    public void setEntityEventPersistence(
        EntityEventPersistence entityEventPersistence) {
        this.entityEventPersistence = entityEventPersistence;
    }

    /**
     * Returns the entity g parameter local service.
     *
     * @return the entity g parameter local service
     */
    public com.consistent.ucwrt.service.EntityGParameterLocalService getEntityGParameterLocalService() {
        return entityGParameterLocalService;
    }

    /**
     * Sets the entity g parameter local service.
     *
     * @param entityGParameterLocalService the entity g parameter local service
     */
    public void setEntityGParameterLocalService(
        com.consistent.ucwrt.service.EntityGParameterLocalService entityGParameterLocalService) {
        this.entityGParameterLocalService = entityGParameterLocalService;
    }

    /**
     * Returns the entity g parameter remote service.
     *
     * @return the entity g parameter remote service
     */
    public com.consistent.ucwrt.service.EntityGParameterService getEntityGParameterService() {
        return entityGParameterService;
    }

    /**
     * Sets the entity g parameter remote service.
     *
     * @param entityGParameterService the entity g parameter remote service
     */
    public void setEntityGParameterService(
        com.consistent.ucwrt.service.EntityGParameterService entityGParameterService) {
        this.entityGParameterService = entityGParameterService;
    }

    /**
     * Returns the entity g parameter persistence.
     *
     * @return the entity g parameter persistence
     */
    public EntityGParameterPersistence getEntityGParameterPersistence() {
        return entityGParameterPersistence;
    }

    /**
     * Sets the entity g parameter persistence.
     *
     * @param entityGParameterPersistence the entity g parameter persistence
     */
    public void setEntityGParameterPersistence(
        EntityGParameterPersistence entityGParameterPersistence) {
        this.entityGParameterPersistence = entityGParameterPersistence;
    }

    /**
     * Returns the entity intervalos local service.
     *
     * @return the entity intervalos local service
     */
    public com.consistent.ucwrt.service.EntityIntervalosLocalService getEntityIntervalosLocalService() {
        return entityIntervalosLocalService;
    }

    /**
     * Sets the entity intervalos local service.
     *
     * @param entityIntervalosLocalService the entity intervalos local service
     */
    public void setEntityIntervalosLocalService(
        com.consistent.ucwrt.service.EntityIntervalosLocalService entityIntervalosLocalService) {
        this.entityIntervalosLocalService = entityIntervalosLocalService;
    }

    /**
     * Returns the entity intervalos remote service.
     *
     * @return the entity intervalos remote service
     */
    public com.consistent.ucwrt.service.EntityIntervalosService getEntityIntervalosService() {
        return entityIntervalosService;
    }

    /**
     * Sets the entity intervalos remote service.
     *
     * @param entityIntervalosService the entity intervalos remote service
     */
    public void setEntityIntervalosService(
        com.consistent.ucwrt.service.EntityIntervalosService entityIntervalosService) {
        this.entityIntervalosService = entityIntervalosService;
    }

    /**
     * Returns the entity intervalos persistence.
     *
     * @return the entity intervalos persistence
     */
    public EntityIntervalosPersistence getEntityIntervalosPersistence() {
        return entityIntervalosPersistence;
    }

    /**
     * Sets the entity intervalos persistence.
     *
     * @param entityIntervalosPersistence the entity intervalos persistence
     */
    public void setEntityIntervalosPersistence(
        EntityIntervalosPersistence entityIntervalosPersistence) {
        this.entityIntervalosPersistence = entityIntervalosPersistence;
    }

    /**
     * Returns the entity inventory local service.
     *
     * @return the entity inventory local service
     */
    public com.consistent.ucwrt.service.EntityInventoryLocalService getEntityInventoryLocalService() {
        return entityInventoryLocalService;
    }

    /**
     * Sets the entity inventory local service.
     *
     * @param entityInventoryLocalService the entity inventory local service
     */
    public void setEntityInventoryLocalService(
        com.consistent.ucwrt.service.EntityInventoryLocalService entityInventoryLocalService) {
        this.entityInventoryLocalService = entityInventoryLocalService;
    }

    /**
     * Returns the entity inventory remote service.
     *
     * @return the entity inventory remote service
     */
    public com.consistent.ucwrt.service.EntityInventoryService getEntityInventoryService() {
        return entityInventoryService;
    }

    /**
     * Sets the entity inventory remote service.
     *
     * @param entityInventoryService the entity inventory remote service
     */
    public void setEntityInventoryService(
        com.consistent.ucwrt.service.EntityInventoryService entityInventoryService) {
        this.entityInventoryService = entityInventoryService;
    }

    /**
     * Returns the entity inventory persistence.
     *
     * @return the entity inventory persistence
     */
    public EntityInventoryPersistence getEntityInventoryPersistence() {
        return entityInventoryPersistence;
    }

    /**
     * Sets the entity inventory persistence.
     *
     * @param entityInventoryPersistence the entity inventory persistence
     */
    public void setEntityInventoryPersistence(
        EntityInventoryPersistence entityInventoryPersistence) {
        this.entityInventoryPersistence = entityInventoryPersistence;
    }

    /**
     * Returns the entity inventory clasification local service.
     *
     * @return the entity inventory clasification local service
     */
    public com.consistent.ucwrt.service.EntityInventoryClasificationLocalService getEntityInventoryClasificationLocalService() {
        return entityInventoryClasificationLocalService;
    }

    /**
     * Sets the entity inventory clasification local service.
     *
     * @param entityInventoryClasificationLocalService the entity inventory clasification local service
     */
    public void setEntityInventoryClasificationLocalService(
        com.consistent.ucwrt.service.EntityInventoryClasificationLocalService entityInventoryClasificationLocalService) {
        this.entityInventoryClasificationLocalService = entityInventoryClasificationLocalService;
    }

    /**
     * Returns the entity inventory clasification remote service.
     *
     * @return the entity inventory clasification remote service
     */
    public com.consistent.ucwrt.service.EntityInventoryClasificationService getEntityInventoryClasificationService() {
        return entityInventoryClasificationService;
    }

    /**
     * Sets the entity inventory clasification remote service.
     *
     * @param entityInventoryClasificationService the entity inventory clasification remote service
     */
    public void setEntityInventoryClasificationService(
        com.consistent.ucwrt.service.EntityInventoryClasificationService entityInventoryClasificationService) {
        this.entityInventoryClasificationService = entityInventoryClasificationService;
    }

    /**
     * Returns the entity inventory clasification persistence.
     *
     * @return the entity inventory clasification persistence
     */
    public EntityInventoryClasificationPersistence getEntityInventoryClasificationPersistence() {
        return entityInventoryClasificationPersistence;
    }

    /**
     * Sets the entity inventory clasification persistence.
     *
     * @param entityInventoryClasificationPersistence the entity inventory clasification persistence
     */
    public void setEntityInventoryClasificationPersistence(
        EntityInventoryClasificationPersistence entityInventoryClasificationPersistence) {
        this.entityInventoryClasificationPersistence = entityInventoryClasificationPersistence;
    }

    /**
     * Returns the entity model local service.
     *
     * @return the entity model local service
     */
    public com.consistent.ucwrt.service.EntityModelLocalService getEntityModelLocalService() {
        return entityModelLocalService;
    }

    /**
     * Sets the entity model local service.
     *
     * @param entityModelLocalService the entity model local service
     */
    public void setEntityModelLocalService(
        com.consistent.ucwrt.service.EntityModelLocalService entityModelLocalService) {
        this.entityModelLocalService = entityModelLocalService;
    }

    /**
     * Returns the entity model remote service.
     *
     * @return the entity model remote service
     */
    public com.consistent.ucwrt.service.EntityModelService getEntityModelService() {
        return entityModelService;
    }

    /**
     * Sets the entity model remote service.
     *
     * @param entityModelService the entity model remote service
     */
    public void setEntityModelService(
        com.consistent.ucwrt.service.EntityModelService entityModelService) {
        this.entityModelService = entityModelService;
    }

    /**
     * Returns the entity model persistence.
     *
     * @return the entity model persistence
     */
    public EntityModelPersistence getEntityModelPersistence() {
        return entityModelPersistence;
    }

    /**
     * Sets the entity model persistence.
     *
     * @param entityModelPersistence the entity model persistence
     */
    public void setEntityModelPersistence(
        EntityModelPersistence entityModelPersistence) {
        this.entityModelPersistence = entityModelPersistence;
    }

    /**
     * Returns the entity monthly sales goal local service.
     *
     * @return the entity monthly sales goal local service
     */
    public com.consistent.ucwrt.service.EntityMonthlySalesGoalLocalService getEntityMonthlySalesGoalLocalService() {
        return entityMonthlySalesGoalLocalService;
    }

    /**
     * Sets the entity monthly sales goal local service.
     *
     * @param entityMonthlySalesGoalLocalService the entity monthly sales goal local service
     */
    public void setEntityMonthlySalesGoalLocalService(
        com.consistent.ucwrt.service.EntityMonthlySalesGoalLocalService entityMonthlySalesGoalLocalService) {
        this.entityMonthlySalesGoalLocalService = entityMonthlySalesGoalLocalService;
    }

    /**
     * Returns the entity monthly sales goal remote service.
     *
     * @return the entity monthly sales goal remote service
     */
    public com.consistent.ucwrt.service.EntityMonthlySalesGoalService getEntityMonthlySalesGoalService() {
        return entityMonthlySalesGoalService;
    }

    /**
     * Sets the entity monthly sales goal remote service.
     *
     * @param entityMonthlySalesGoalService the entity monthly sales goal remote service
     */
    public void setEntityMonthlySalesGoalService(
        com.consistent.ucwrt.service.EntityMonthlySalesGoalService entityMonthlySalesGoalService) {
        this.entityMonthlySalesGoalService = entityMonthlySalesGoalService;
    }

    /**
     * Returns the entity monthly sales goal persistence.
     *
     * @return the entity monthly sales goal persistence
     */
    public EntityMonthlySalesGoalPersistence getEntityMonthlySalesGoalPersistence() {
        return entityMonthlySalesGoalPersistence;
    }

    /**
     * Sets the entity monthly sales goal persistence.
     *
     * @param entityMonthlySalesGoalPersistence the entity monthly sales goal persistence
     */
    public void setEntityMonthlySalesGoalPersistence(
        EntityMonthlySalesGoalPersistence entityMonthlySalesGoalPersistence) {
        this.entityMonthlySalesGoalPersistence = entityMonthlySalesGoalPersistence;
    }

    /**
     * Returns the entity municipality local service.
     *
     * @return the entity municipality local service
     */
    public com.consistent.ucwrt.service.EntityMunicipalityLocalService getEntityMunicipalityLocalService() {
        return entityMunicipalityLocalService;
    }

    /**
     * Sets the entity municipality local service.
     *
     * @param entityMunicipalityLocalService the entity municipality local service
     */
    public void setEntityMunicipalityLocalService(
        com.consistent.ucwrt.service.EntityMunicipalityLocalService entityMunicipalityLocalService) {
        this.entityMunicipalityLocalService = entityMunicipalityLocalService;
    }

    /**
     * Returns the entity municipality remote service.
     *
     * @return the entity municipality remote service
     */
    public com.consistent.ucwrt.service.EntityMunicipalityService getEntityMunicipalityService() {
        return entityMunicipalityService;
    }

    /**
     * Sets the entity municipality remote service.
     *
     * @param entityMunicipalityService the entity municipality remote service
     */
    public void setEntityMunicipalityService(
        com.consistent.ucwrt.service.EntityMunicipalityService entityMunicipalityService) {
        this.entityMunicipalityService = entityMunicipalityService;
    }

    /**
     * Returns the entity municipality persistence.
     *
     * @return the entity municipality persistence
     */
    public EntityMunicipalityPersistence getEntityMunicipalityPersistence() {
        return entityMunicipalityPersistence;
    }

    /**
     * Sets the entity municipality persistence.
     *
     * @param entityMunicipalityPersistence the entity municipality persistence
     */
    public void setEntityMunicipalityPersistence(
        EntityMunicipalityPersistence entityMunicipalityPersistence) {
        this.entityMunicipalityPersistence = entityMunicipalityPersistence;
    }

    /**
     * Returns the entity prospection local service.
     *
     * @return the entity prospection local service
     */
    public com.consistent.ucwrt.service.EntityProspectionLocalService getEntityProspectionLocalService() {
        return entityProspectionLocalService;
    }

    /**
     * Sets the entity prospection local service.
     *
     * @param entityProspectionLocalService the entity prospection local service
     */
    public void setEntityProspectionLocalService(
        com.consistent.ucwrt.service.EntityProspectionLocalService entityProspectionLocalService) {
        this.entityProspectionLocalService = entityProspectionLocalService;
    }

    /**
     * Returns the entity prospection remote service.
     *
     * @return the entity prospection remote service
     */
    public com.consistent.ucwrt.service.EntityProspectionService getEntityProspectionService() {
        return entityProspectionService;
    }

    /**
     * Sets the entity prospection remote service.
     *
     * @param entityProspectionService the entity prospection remote service
     */
    public void setEntityProspectionService(
        com.consistent.ucwrt.service.EntityProspectionService entityProspectionService) {
        this.entityProspectionService = entityProspectionService;
    }

    /**
     * Returns the entity prospection persistence.
     *
     * @return the entity prospection persistence
     */
    public EntityProspectionPersistence getEntityProspectionPersistence() {
        return entityProspectionPersistence;
    }

    /**
     * Sets the entity prospection persistence.
     *
     * @param entityProspectionPersistence the entity prospection persistence
     */
    public void setEntityProspectionPersistence(
        EntityProspectionPersistence entityProspectionPersistence) {
        this.entityProspectionPersistence = entityProspectionPersistence;
    }

    /**
     * Returns the entity sale local service.
     *
     * @return the entity sale local service
     */
    public com.consistent.ucwrt.service.EntitySaleLocalService getEntitySaleLocalService() {
        return entitySaleLocalService;
    }

    /**
     * Sets the entity sale local service.
     *
     * @param entitySaleLocalService the entity sale local service
     */
    public void setEntitySaleLocalService(
        com.consistent.ucwrt.service.EntitySaleLocalService entitySaleLocalService) {
        this.entitySaleLocalService = entitySaleLocalService;
    }

    /**
     * Returns the entity sale remote service.
     *
     * @return the entity sale remote service
     */
    public com.consistent.ucwrt.service.EntitySaleService getEntitySaleService() {
        return entitySaleService;
    }

    /**
     * Sets the entity sale remote service.
     *
     * @param entitySaleService the entity sale remote service
     */
    public void setEntitySaleService(
        com.consistent.ucwrt.service.EntitySaleService entitySaleService) {
        this.entitySaleService = entitySaleService;
    }

    /**
     * Returns the entity sale persistence.
     *
     * @return the entity sale persistence
     */
    public EntitySalePersistence getEntitySalePersistence() {
        return entitySalePersistence;
    }

    /**
     * Sets the entity sale persistence.
     *
     * @param entitySalePersistence the entity sale persistence
     */
    public void setEntitySalePersistence(
        EntitySalePersistence entitySalePersistence) {
        this.entitySalePersistence = entitySalePersistence;
    }

    /**
     * Returns the entity sales place local service.
     *
     * @return the entity sales place local service
     */
    public com.consistent.ucwrt.service.EntitySalesPlaceLocalService getEntitySalesPlaceLocalService() {
        return entitySalesPlaceLocalService;
    }

    /**
     * Sets the entity sales place local service.
     *
     * @param entitySalesPlaceLocalService the entity sales place local service
     */
    public void setEntitySalesPlaceLocalService(
        com.consistent.ucwrt.service.EntitySalesPlaceLocalService entitySalesPlaceLocalService) {
        this.entitySalesPlaceLocalService = entitySalesPlaceLocalService;
    }

    /**
     * Returns the entity sales place remote service.
     *
     * @return the entity sales place remote service
     */
    public com.consistent.ucwrt.service.EntitySalesPlaceService getEntitySalesPlaceService() {
        return entitySalesPlaceService;
    }

    /**
     * Sets the entity sales place remote service.
     *
     * @param entitySalesPlaceService the entity sales place remote service
     */
    public void setEntitySalesPlaceService(
        com.consistent.ucwrt.service.EntitySalesPlaceService entitySalesPlaceService) {
        this.entitySalesPlaceService = entitySalesPlaceService;
    }

    /**
     * Returns the entity sales place persistence.
     *
     * @return the entity sales place persistence
     */
    public EntitySalesPlacePersistence getEntitySalesPlacePersistence() {
        return entitySalesPlacePersistence;
    }

    /**
     * Sets the entity sales place persistence.
     *
     * @param entitySalesPlacePersistence the entity sales place persistence
     */
    public void setEntitySalesPlacePersistence(
        EntitySalesPlacePersistence entitySalesPlacePersistence) {
        this.entitySalesPlacePersistence = entitySalesPlacePersistence;
    }

    /**
     * Returns the entity source of supply local service.
     *
     * @return the entity source of supply local service
     */
    public com.consistent.ucwrt.service.EntitySourceOfSupplyLocalService getEntitySourceOfSupplyLocalService() {
        return entitySourceOfSupplyLocalService;
    }

    /**
     * Sets the entity source of supply local service.
     *
     * @param entitySourceOfSupplyLocalService the entity source of supply local service
     */
    public void setEntitySourceOfSupplyLocalService(
        com.consistent.ucwrt.service.EntitySourceOfSupplyLocalService entitySourceOfSupplyLocalService) {
        this.entitySourceOfSupplyLocalService = entitySourceOfSupplyLocalService;
    }

    /**
     * Returns the entity source of supply remote service.
     *
     * @return the entity source of supply remote service
     */
    public com.consistent.ucwrt.service.EntitySourceOfSupplyService getEntitySourceOfSupplyService() {
        return entitySourceOfSupplyService;
    }

    /**
     * Sets the entity source of supply remote service.
     *
     * @param entitySourceOfSupplyService the entity source of supply remote service
     */
    public void setEntitySourceOfSupplyService(
        com.consistent.ucwrt.service.EntitySourceOfSupplyService entitySourceOfSupplyService) {
        this.entitySourceOfSupplyService = entitySourceOfSupplyService;
    }

    /**
     * Returns the entity source of supply persistence.
     *
     * @return the entity source of supply persistence
     */
    public EntitySourceOfSupplyPersistence getEntitySourceOfSupplyPersistence() {
        return entitySourceOfSupplyPersistence;
    }

    /**
     * Sets the entity source of supply persistence.
     *
     * @param entitySourceOfSupplyPersistence the entity source of supply persistence
     */
    public void setEntitySourceOfSupplyPersistence(
        EntitySourceOfSupplyPersistence entitySourceOfSupplyPersistence) {
        this.entitySourceOfSupplyPersistence = entitySourceOfSupplyPersistence;
    }

    /**
     * Returns the entity state local service.
     *
     * @return the entity state local service
     */
    public com.consistent.ucwrt.service.EntityStateLocalService getEntityStateLocalService() {
        return entityStateLocalService;
    }

    /**
     * Sets the entity state local service.
     *
     * @param entityStateLocalService the entity state local service
     */
    public void setEntityStateLocalService(
        com.consistent.ucwrt.service.EntityStateLocalService entityStateLocalService) {
        this.entityStateLocalService = entityStateLocalService;
    }

    /**
     * Returns the entity state remote service.
     *
     * @return the entity state remote service
     */
    public com.consistent.ucwrt.service.EntityStateService getEntityStateService() {
        return entityStateService;
    }

    /**
     * Sets the entity state remote service.
     *
     * @param entityStateService the entity state remote service
     */
    public void setEntityStateService(
        com.consistent.ucwrt.service.EntityStateService entityStateService) {
        this.entityStateService = entityStateService;
    }

    /**
     * Returns the entity state persistence.
     *
     * @return the entity state persistence
     */
    public EntityStatePersistence getEntityStatePersistence() {
        return entityStatePersistence;
    }

    /**
     * Sets the entity state persistence.
     *
     * @param entityStatePersistence the entity state persistence
     */
    public void setEntityStatePersistence(
        EntityStatePersistence entityStatePersistence) {
        this.entityStatePersistence = entityStatePersistence;
    }

    /**
     * Returns the entity status local service.
     *
     * @return the entity status local service
     */
    public com.consistent.ucwrt.service.EntityStatusLocalService getEntityStatusLocalService() {
        return entityStatusLocalService;
    }

    /**
     * Sets the entity status local service.
     *
     * @param entityStatusLocalService the entity status local service
     */
    public void setEntityStatusLocalService(
        com.consistent.ucwrt.service.EntityStatusLocalService entityStatusLocalService) {
        this.entityStatusLocalService = entityStatusLocalService;
    }

    /**
     * Returns the entity status remote service.
     *
     * @return the entity status remote service
     */
    public com.consistent.ucwrt.service.EntityStatusService getEntityStatusService() {
        return entityStatusService;
    }

    /**
     * Sets the entity status remote service.
     *
     * @param entityStatusService the entity status remote service
     */
    public void setEntityStatusService(
        com.consistent.ucwrt.service.EntityStatusService entityStatusService) {
        this.entityStatusService = entityStatusService;
    }

    /**
     * Returns the entity status persistence.
     *
     * @return the entity status persistence
     */
    public EntityStatusPersistence getEntityStatusPersistence() {
        return entityStatusPersistence;
    }

    /**
     * Sets the entity status persistence.
     *
     * @param entityStatusPersistence the entity status persistence
     */
    public void setEntityStatusPersistence(
        EntityStatusPersistence entityStatusPersistence) {
        this.entityStatusPersistence = entityStatusPersistence;
    }

    /**
     * Returns the entity suburb local service.
     *
     * @return the entity suburb local service
     */
    public com.consistent.ucwrt.service.EntitySuburbLocalService getEntitySuburbLocalService() {
        return entitySuburbLocalService;
    }

    /**
     * Sets the entity suburb local service.
     *
     * @param entitySuburbLocalService the entity suburb local service
     */
    public void setEntitySuburbLocalService(
        com.consistent.ucwrt.service.EntitySuburbLocalService entitySuburbLocalService) {
        this.entitySuburbLocalService = entitySuburbLocalService;
    }

    /**
     * Returns the entity suburb remote service.
     *
     * @return the entity suburb remote service
     */
    public com.consistent.ucwrt.service.EntitySuburbService getEntitySuburbService() {
        return entitySuburbService;
    }

    /**
     * Sets the entity suburb remote service.
     *
     * @param entitySuburbService the entity suburb remote service
     */
    public void setEntitySuburbService(
        com.consistent.ucwrt.service.EntitySuburbService entitySuburbService) {
        this.entitySuburbService = entitySuburbService;
    }

    /**
     * Returns the entity suburb persistence.
     *
     * @return the entity suburb persistence
     */
    public EntitySuburbPersistence getEntitySuburbPersistence() {
        return entitySuburbPersistence;
    }

    /**
     * Sets the entity suburb persistence.
     *
     * @param entitySuburbPersistence the entity suburb persistence
     */
    public void setEntitySuburbPersistence(
        EntitySuburbPersistence entitySuburbPersistence) {
        this.entitySuburbPersistence = entitySuburbPersistence;
    }

    /**
     * Returns the entity version auto local service.
     *
     * @return the entity version auto local service
     */
    public com.consistent.ucwrt.service.EntityVersionAutoLocalService getEntityVersionAutoLocalService() {
        return entityVersionAutoLocalService;
    }

    /**
     * Sets the entity version auto local service.
     *
     * @param entityVersionAutoLocalService the entity version auto local service
     */
    public void setEntityVersionAutoLocalService(
        com.consistent.ucwrt.service.EntityVersionAutoLocalService entityVersionAutoLocalService) {
        this.entityVersionAutoLocalService = entityVersionAutoLocalService;
    }

    /**
     * Returns the entity version auto remote service.
     *
     * @return the entity version auto remote service
     */
    public com.consistent.ucwrt.service.EntityVersionAutoService getEntityVersionAutoService() {
        return entityVersionAutoService;
    }

    /**
     * Sets the entity version auto remote service.
     *
     * @param entityVersionAutoService the entity version auto remote service
     */
    public void setEntityVersionAutoService(
        com.consistent.ucwrt.service.EntityVersionAutoService entityVersionAutoService) {
        this.entityVersionAutoService = entityVersionAutoService;
    }

    /**
     * Returns the entity version auto persistence.
     *
     * @return the entity version auto persistence
     */
    public EntityVersionAutoPersistence getEntityVersionAutoPersistence() {
        return entityVersionAutoPersistence;
    }

    /**
     * Sets the entity version auto persistence.
     *
     * @param entityVersionAutoPersistence the entity version auto persistence
     */
    public void setEntityVersionAutoPersistence(
        EntityVersionAutoPersistence entityVersionAutoPersistence) {
        this.entityVersionAutoPersistence = entityVersionAutoPersistence;
    }

    /**
     * Returns the entity version equipment local service.
     *
     * @return the entity version equipment local service
     */
    public com.consistent.ucwrt.service.EntityVersionEquipmentLocalService getEntityVersionEquipmentLocalService() {
        return entityVersionEquipmentLocalService;
    }

    /**
     * Sets the entity version equipment local service.
     *
     * @param entityVersionEquipmentLocalService the entity version equipment local service
     */
    public void setEntityVersionEquipmentLocalService(
        com.consistent.ucwrt.service.EntityVersionEquipmentLocalService entityVersionEquipmentLocalService) {
        this.entityVersionEquipmentLocalService = entityVersionEquipmentLocalService;
    }

    /**
     * Returns the entity version equipment remote service.
     *
     * @return the entity version equipment remote service
     */
    public com.consistent.ucwrt.service.EntityVersionEquipmentService getEntityVersionEquipmentService() {
        return entityVersionEquipmentService;
    }

    /**
     * Sets the entity version equipment remote service.
     *
     * @param entityVersionEquipmentService the entity version equipment remote service
     */
    public void setEntityVersionEquipmentService(
        com.consistent.ucwrt.service.EntityVersionEquipmentService entityVersionEquipmentService) {
        this.entityVersionEquipmentService = entityVersionEquipmentService;
    }

    /**
     * Returns the entity version equipment persistence.
     *
     * @return the entity version equipment persistence
     */
    public EntityVersionEquipmentPersistence getEntityVersionEquipmentPersistence() {
        return entityVersionEquipmentPersistence;
    }

    /**
     * Sets the entity version equipment persistence.
     *
     * @param entityVersionEquipmentPersistence the entity version equipment persistence
     */
    public void setEntityVersionEquipmentPersistence(
        EntityVersionEquipmentPersistence entityVersionEquipmentPersistence) {
        this.entityVersionEquipmentPersistence = entityVersionEquipmentPersistence;
    }

    /**
     * Returns the entity way to pay local service.
     *
     * @return the entity way to pay local service
     */
    public com.consistent.ucwrt.service.EntityWayToPayLocalService getEntityWayToPayLocalService() {
        return entityWayToPayLocalService;
    }

    /**
     * Sets the entity way to pay local service.
     *
     * @param entityWayToPayLocalService the entity way to pay local service
     */
    public void setEntityWayToPayLocalService(
        com.consistent.ucwrt.service.EntityWayToPayLocalService entityWayToPayLocalService) {
        this.entityWayToPayLocalService = entityWayToPayLocalService;
    }

    /**
     * Returns the entity way to pay remote service.
     *
     * @return the entity way to pay remote service
     */
    public com.consistent.ucwrt.service.EntityWayToPayService getEntityWayToPayService() {
        return entityWayToPayService;
    }

    /**
     * Sets the entity way to pay remote service.
     *
     * @param entityWayToPayService the entity way to pay remote service
     */
    public void setEntityWayToPayService(
        com.consistent.ucwrt.service.EntityWayToPayService entityWayToPayService) {
        this.entityWayToPayService = entityWayToPayService;
    }

    /**
     * Returns the entity way to pay persistence.
     *
     * @return the entity way to pay persistence
     */
    public EntityWayToPayPersistence getEntityWayToPayPersistence() {
        return entityWayToPayPersistence;
    }

    /**
     * Sets the entity way to pay persistence.
     *
     * @param entityWayToPayPersistence the entity way to pay persistence
     */
    public void setEntityWayToPayPersistence(
        EntityWayToPayPersistence entityWayToPayPersistence) {
        this.entityWayToPayPersistence = entityWayToPayPersistence;
    }

    /**
     * Returns the entity year model local service.
     *
     * @return the entity year model local service
     */
    public com.consistent.ucwrt.service.EntityYearModelLocalService getEntityYearModelLocalService() {
        return entityYearModelLocalService;
    }

    /**
     * Sets the entity year model local service.
     *
     * @param entityYearModelLocalService the entity year model local service
     */
    public void setEntityYearModelLocalService(
        com.consistent.ucwrt.service.EntityYearModelLocalService entityYearModelLocalService) {
        this.entityYearModelLocalService = entityYearModelLocalService;
    }

    /**
     * Returns the entity year model remote service.
     *
     * @return the entity year model remote service
     */
    public com.consistent.ucwrt.service.EntityYearModelService getEntityYearModelService() {
        return entityYearModelService;
    }

    /**
     * Sets the entity year model remote service.
     *
     * @param entityYearModelService the entity year model remote service
     */
    public void setEntityYearModelService(
        com.consistent.ucwrt.service.EntityYearModelService entityYearModelService) {
        this.entityYearModelService = entityYearModelService;
    }

    /**
     * Returns the entity year model persistence.
     *
     * @return the entity year model persistence
     */
    public EntityYearModelPersistence getEntityYearModelPersistence() {
        return entityYearModelPersistence;
    }

    /**
     * Sets the entity year model persistence.
     *
     * @param entityYearModelPersistence the entity year model persistence
     */
    public void setEntityYearModelPersistence(
        EntityYearModelPersistence entityYearModelPersistence) {
        this.entityYearModelPersistence = entityYearModelPersistence;
    }

    /**
     * Returns the entity year model class local service.
     *
     * @return the entity year model class local service
     */
    public com.consistent.ucwrt.service.EntityYearModelClassLocalService getEntityYearModelClassLocalService() {
        return entityYearModelClassLocalService;
    }

    /**
     * Sets the entity year model class local service.
     *
     * @param entityYearModelClassLocalService the entity year model class local service
     */
    public void setEntityYearModelClassLocalService(
        com.consistent.ucwrt.service.EntityYearModelClassLocalService entityYearModelClassLocalService) {
        this.entityYearModelClassLocalService = entityYearModelClassLocalService;
    }

    /**
     * Returns the entity year model class remote service.
     *
     * @return the entity year model class remote service
     */
    public com.consistent.ucwrt.service.EntityYearModelClassService getEntityYearModelClassService() {
        return entityYearModelClassService;
    }

    /**
     * Sets the entity year model class remote service.
     *
     * @param entityYearModelClassService the entity year model class remote service
     */
    public void setEntityYearModelClassService(
        com.consistent.ucwrt.service.EntityYearModelClassService entityYearModelClassService) {
        this.entityYearModelClassService = entityYearModelClassService;
    }

    /**
     * Returns the entity year model class persistence.
     *
     * @return the entity year model class persistence
     */
    public EntityYearModelClassPersistence getEntityYearModelClassPersistence() {
        return entityYearModelClassPersistence;
    }

    /**
     * Sets the entity year model class persistence.
     *
     * @param entityYearModelClassPersistence the entity year model class persistence
     */
    public void setEntityYearModelClassPersistence(
        EntityYearModelClassPersistence entityYearModelClassPersistence) {
        this.entityYearModelClassPersistence = entityYearModelClassPersistence;
    }

    /**
     * Returns the entity zone local service.
     *
     * @return the entity zone local service
     */
    public com.consistent.ucwrt.service.EntityZoneLocalService getEntityZoneLocalService() {
        return entityZoneLocalService;
    }

    /**
     * Sets the entity zone local service.
     *
     * @param entityZoneLocalService the entity zone local service
     */
    public void setEntityZoneLocalService(
        com.consistent.ucwrt.service.EntityZoneLocalService entityZoneLocalService) {
        this.entityZoneLocalService = entityZoneLocalService;
    }

    /**
     * Returns the entity zone remote service.
     *
     * @return the entity zone remote service
     */
    public com.consistent.ucwrt.service.EntityZoneService getEntityZoneService() {
        return entityZoneService;
    }

    /**
     * Sets the entity zone remote service.
     *
     * @param entityZoneService the entity zone remote service
     */
    public void setEntityZoneService(
        com.consistent.ucwrt.service.EntityZoneService entityZoneService) {
        this.entityZoneService = entityZoneService;
    }

    /**
     * Returns the entity zone persistence.
     *
     * @return the entity zone persistence
     */
    public EntityZonePersistence getEntityZonePersistence() {
        return entityZonePersistence;
    }

    /**
     * Sets the entity zone persistence.
     *
     * @param entityZonePersistence the entity zone persistence
     */
    public void setEntityZonePersistence(
        EntityZonePersistence entityZonePersistence) {
        this.entityZonePersistence = entityZonePersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();

        PersistedModelLocalServiceRegistryUtil.register("com.consistent.ucwrt.model.EntityEvent",
            entityEventLocalService);
    }

    public void destroy() {
        PersistedModelLocalServiceRegistryUtil.unregister(
            "com.consistent.ucwrt.model.EntityEvent");
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return EntityEvent.class;
    }

    protected String getModelClassName() {
        return EntityEvent.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = entityEventPersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
