package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityBusinessBrand service. Represents a row in the &quot;BusinessBrand&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityBusinessBrandModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityBusinessBrandImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityBusinessBrand
 * @see com.consistent.ucwrt.model.impl.EntityBusinessBrandImpl
 * @see com.consistent.ucwrt.model.impl.EntityBusinessBrandModelImpl
 * @generated
 */
public interface EntityBusinessBrandModel extends BaseModel<EntityBusinessBrand> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity business brand model instance should use the {@link EntityBusinessBrand} interface instead.
     */

    /**
     * Returns the primary key of this entity business brand.
     *
     * @return the primary key of this entity business brand
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this entity business brand.
     *
     * @param primaryKey the primary key of this entity business brand
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the business brand name of this entity business brand.
     *
     * @return the business brand name of this entity business brand
     */
    @AutoEscape
    public String getBusinessBrandName();

    /**
     * Sets the business brand name of this entity business brand.
     *
     * @param businessBrandName the business brand name of this entity business brand
     */
    public void setBusinessBrandName(String businessBrandName);

    /**
     * Returns the description business brand of this entity business brand.
     *
     * @return the description business brand of this entity business brand
     */
    @AutoEscape
    public String getDescriptionBusinessBrand();

    /**
     * Sets the description business brand of this entity business brand.
     *
     * @param descriptionBusinessBrand the description business brand of this entity business brand
     */
    public void setDescriptionBusinessBrand(String descriptionBusinessBrand);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityBusinessBrand entityBusinessBrand);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityBusinessBrand> toCacheModel();

    @Override
    public EntityBusinessBrand toEscapedModel();

    @Override
    public EntityBusinessBrand toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
