package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityState service. Represents a row in the &quot;State&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityStateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityStateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityState
 * @see com.consistent.ucwrt.model.impl.EntityStateImpl
 * @see com.consistent.ucwrt.model.impl.EntityStateModelImpl
 * @generated
 */
public interface EntityStateModel extends BaseModel<EntityState> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity state model instance should use the {@link EntityState} interface instead.
     */

    /**
     * Returns the primary key of this entity state.
     *
     * @return the primary key of this entity state
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity state.
     *
     * @param primaryKey the primary key of this entity state
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the state ID of this entity state.
     *
     * @return the state ID of this entity state
     */
    public int getStateId();

    /**
     * Sets the state ID of this entity state.
     *
     * @param stateId the state ID of this entity state
     */
    public void setStateId(int stateId);

    /**
     * Returns the state name of this entity state.
     *
     * @return the state name of this entity state
     */
    @AutoEscape
    public String getStateName();

    /**
     * Sets the state name of this entity state.
     *
     * @param stateName the state name of this entity state
     */
    public void setStateName(String stateName);

    /**
     * Returns the capital name of this entity state.
     *
     * @return the capital name of this entity state
     */
    @AutoEscape
    public String getCapitalName();

    /**
     * Sets the capital name of this entity state.
     *
     * @param capitalName the capital name of this entity state
     */
    public void setCapitalName(String capitalName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityState entityState);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityState> toCacheModel();

    @Override
    public EntityState toEscapedModel();

    @Override
    public EntityState toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
