package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EntityYearModel service. Represents a row in the &quot;YearModel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityYearModelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityYearModelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityYearModel
 * @see com.consistent.ucwrt.model.impl.EntityYearModelImpl
 * @see com.consistent.ucwrt.model.impl.EntityYearModelModelImpl
 * @generated
 */
public interface EntityYearModelModel extends BaseModel<EntityYearModel> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity year model model instance should use the {@link EntityYearModel} interface instead.
     */

    /**
     * Returns the primary key of this entity year model.
     *
     * @return the primary key of this entity year model
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity year model.
     *
     * @param primaryKey the primary key of this entity year model
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the year model of this entity year model.
     *
     * @return the year model of this entity year model
     */
    public int getYearModel();

    /**
     * Sets the year model of this entity year model.
     *
     * @param yearModel the year model of this entity year model
     */
    public void setYearModel(int yearModel);

    /**
     * Returns the year model registration date of this entity year model.
     *
     * @return the year model registration date of this entity year model
     */
    public Date getYearModelRegistrationDate();

    /**
     * Sets the year model registration date of this entity year model.
     *
     * @param yearModelRegistrationDate the year model registration date of this entity year model
     */
    public void setYearModelRegistrationDate(Date yearModelRegistrationDate);

    /**
     * Returns the year model register data of this entity year model.
     *
     * @return the year model register data of this entity year model
     */
    @AutoEscape
    public String getYearModelRegisterData();

    /**
     * Sets the year model register data of this entity year model.
     *
     * @param yearModelRegisterData the year model register data of this entity year model
     */
    public void setYearModelRegisterData(String yearModelRegisterData);

    /**
     * Returns the y model responsible user of this entity year model.
     *
     * @return the y model responsible user of this entity year model
     */
    @AutoEscape
    public String getYModelResponsibleUser();

    /**
     * Sets the y model responsible user of this entity year model.
     *
     * @param yModelResponsibleUser the y model responsible user of this entity year model
     */
    public void setYModelResponsibleUser(String yModelResponsibleUser);

    /**
     * Returns the year model description of this entity year model.
     *
     * @return the year model description of this entity year model
     */
    @AutoEscape
    public String getYearModelDescription();

    /**
     * Sets the year model description of this entity year model.
     *
     * @param yearModelDescription the year model description of this entity year model
     */
    public void setYearModelDescription(String yearModelDescription);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityYearModel entityYearModel);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityYearModel> toCacheModel();

    @Override
    public EntityYearModel toEscapedModel();

    @Override
    public EntityYearModel toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
