package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityMunicipality service. Represents a row in the &quot;Municipality&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityMunicipalityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityMunicipalityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityMunicipality
 * @see com.consistent.ucwrt.model.impl.EntityMunicipalityImpl
 * @see com.consistent.ucwrt.model.impl.EntityMunicipalityModelImpl
 * @generated
 */
public interface EntityMunicipalityModel extends BaseModel<EntityMunicipality> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity municipality model instance should use the {@link EntityMunicipality} interface instead.
     */

    /**
     * Returns the primary key of this entity municipality.
     *
     * @return the primary key of this entity municipality
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity municipality.
     *
     * @param primaryKey the primary key of this entity municipality
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the municipal ID of this entity municipality.
     *
     * @return the municipal ID of this entity municipality
     */
    public int getMunicipalId();

    /**
     * Sets the municipal ID of this entity municipality.
     *
     * @param municipalId the municipal ID of this entity municipality
     */
    public void setMunicipalId(int municipalId);

    /**
     * Returns the municipal name of this entity municipality.
     *
     * @return the municipal name of this entity municipality
     */
    @AutoEscape
    public String getMunicipalName();

    /**
     * Sets the municipal name of this entity municipality.
     *
     * @param municipalName the municipal name of this entity municipality
     */
    public void setMunicipalName(String municipalName);

    /**
     * Returns the state ID of this entity municipality.
     *
     * @return the state ID of this entity municipality
     */
    public int getStateId();

    /**
     * Sets the state ID of this entity municipality.
     *
     * @param stateId the state ID of this entity municipality
     */
    public void setStateId(int stateId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityMunicipality entityMunicipality);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityMunicipality> toCacheModel();

    @Override
    public EntityMunicipality toEscapedModel();

    @Override
    public EntityMunicipality toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
