package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityEquipment service. Represents a row in the &quot;Equipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityEquipmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityEquipmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityEquipment
 * @see com.consistent.ucwrt.model.impl.EntityEquipmentImpl
 * @see com.consistent.ucwrt.model.impl.EntityEquipmentModelImpl
 * @generated
 */
public interface EntityEquipmentModel extends BaseModel<EntityEquipment> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity equipment model instance should use the {@link EntityEquipment} interface instead.
     */

    /**
     * Returns the primary key of this entity equipment.
     *
     * @return the primary key of this entity equipment
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity equipment.
     *
     * @param primaryKey the primary key of this entity equipment
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the equipment ID of this entity equipment.
     *
     * @return the equipment ID of this entity equipment
     */
    public int getEquipmentId();

    /**
     * Sets the equipment ID of this entity equipment.
     *
     * @param equipmentId the equipment ID of this entity equipment
     */
    public void setEquipmentId(int equipmentId);

    /**
     * Returns the equipment description of this entity equipment.
     *
     * @return the equipment description of this entity equipment
     */
    @AutoEscape
    public String getEquipmentDescription();

    /**
     * Sets the equipment description of this entity equipment.
     *
     * @param equipmentDescription the equipment description of this entity equipment
     */
    public void setEquipmentDescription(String equipmentDescription);

    /**
     * Returns the equipment purchase price of this entity equipment.
     *
     * @return the equipment purchase price of this entity equipment
     */
    public double getEquipmentPurchasePrice();

    /**
     * Sets the equipment purchase price of this entity equipment.
     *
     * @param equipmentPurchasePrice the equipment purchase price of this entity equipment
     */
    public void setEquipmentPurchasePrice(double equipmentPurchasePrice);

    /**
     * Returns the equipment purchase price dll of this entity equipment.
     *
     * @return the equipment purchase price dll of this entity equipment
     */
    public double getEquipmentPurchasePriceDll();

    /**
     * Sets the equipment purchase price dll of this entity equipment.
     *
     * @param equipmentPurchasePriceDll the equipment purchase price dll of this entity equipment
     */
    public void setEquipmentPurchasePriceDll(double equipmentPurchasePriceDll);

    /**
     * Returns the equipment sale price of this entity equipment.
     *
     * @return the equipment sale price of this entity equipment
     */
    public double getEquipmentSalePrice();

    /**
     * Sets the equipment sale price of this entity equipment.
     *
     * @param equipmentSalePrice the equipment sale price of this entity equipment
     */
    public void setEquipmentSalePrice(double equipmentSalePrice);

    /**
     * Returns the status of this entity equipment.
     *
     * @return the status of this entity equipment
     */
    @AutoEscape
    public String getStatus();

    /**
     * Sets the status of this entity equipment.
     *
     * @param status the status of this entity equipment
     */
    public void setStatus(String status);

    /**
     * Returns the model ID of this entity equipment.
     *
     * @return the model ID of this entity equipment
     */
    public int getModelId();

    /**
     * Sets the model ID of this entity equipment.
     *
     * @param modelId the model ID of this entity equipment
     */
    public void setModelId(int modelId);

    /**
     * Returns the brand ID of this entity equipment.
     *
     * @return the brand ID of this entity equipment
     */
    public int getBrandId();

    /**
     * Sets the brand ID of this entity equipment.
     *
     * @param brandId the brand ID of this entity equipment
     */
    public void setBrandId(int brandId);

    /**
     * Returns the year model of this entity equipment.
     *
     * @return the year model of this entity equipment
     */
    public int getYearModel();

    /**
     * Sets the year model of this entity equipment.
     *
     * @param yearModel the year model of this entity equipment
     */
    public void setYearModel(int yearModel);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityEquipment entityEquipment);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityEquipment> toCacheModel();

    @Override
    public EntityEquipment toEscapedModel();

    @Override
    public EntityEquipment toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
