package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityDealer service. Represents a row in the &quot;Dealer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityDealerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityDealerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityDealer
 * @see com.consistent.ucwrt.model.impl.EntityDealerImpl
 * @see com.consistent.ucwrt.model.impl.EntityDealerModelImpl
 * @generated
 */
public interface EntityDealerModel extends BaseModel<EntityDealer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity dealer model instance should use the {@link EntityDealer} interface instead.
     */

    /**
     * Returns the primary key of this entity dealer.
     *
     * @return the primary key of this entity dealer
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this entity dealer.
     *
     * @param primaryKey the primary key of this entity dealer
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the dealer ID of this entity dealer.
     *
     * @return the dealer ID of this entity dealer
     */
    @AutoEscape
    public String getDealerId();

    /**
     * Sets the dealer ID of this entity dealer.
     *
     * @param dealerId the dealer ID of this entity dealer
     */
    public void setDealerId(String dealerId);

    /**
     * Returns the dealer name of this entity dealer.
     *
     * @return the dealer name of this entity dealer
     */
    @AutoEscape
    public String getDealerName();

    /**
     * Sets the dealer name of this entity dealer.
     *
     * @param dealerName the dealer name of this entity dealer
     */
    public void setDealerName(String dealerName);

    /**
     * Returns the guaranteed of this entity dealer.
     *
     * @return the guaranteed of this entity dealer
     */
    @AutoEscape
    public String getGuaranteed();

    /**
     * Sets the guaranteed of this entity dealer.
     *
     * @param guaranteed the guaranteed of this entity dealer
     */
    public void setGuaranteed(String guaranteed);

    /**
     * Returns the general manager name of this entity dealer.
     *
     * @return the general manager name of this entity dealer
     */
    @AutoEscape
    public String getGeneralManagerName();

    /**
     * Sets the general manager name of this entity dealer.
     *
     * @param generalManagerName the general manager name of this entity dealer
     */
    public void setGeneralManagerName(String generalManagerName);

    /**
     * Returns the shareholder name of this entity dealer.
     *
     * @return the shareholder name of this entity dealer
     */
    @AutoEscape
    public String getShareholderName();

    /**
     * Sets the shareholder name of this entity dealer.
     *
     * @param shareholderName the shareholder name of this entity dealer
     */
    public void setShareholderName(String shareholderName);

    /**
     * Returns the mail shareholder of this entity dealer.
     *
     * @return the mail shareholder of this entity dealer
     */
    @AutoEscape
    public String getMailShareholder();

    /**
     * Sets the mail shareholder of this entity dealer.
     *
     * @param mailShareholder the mail shareholder of this entity dealer
     */
    public void setMailShareholder(String mailShareholder);

    /**
     * Returns the mail general manager of this entity dealer.
     *
     * @return the mail general manager of this entity dealer
     */
    @AutoEscape
    public String getMailGeneralManager();

    /**
     * Sets the mail general manager of this entity dealer.
     *
     * @param mailGeneralManager the mail general manager of this entity dealer
     */
    public void setMailGeneralManager(String mailGeneralManager);

    /**
     * Returns the business brand name of this entity dealer.
     *
     * @return the business brand name of this entity dealer
     */
    @AutoEscape
    public String getBusinessBrandName();

    /**
     * Sets the business brand name of this entity dealer.
     *
     * @param businessBrandName the business brand name of this entity dealer
     */
    public void setBusinessBrandName(String businessBrandName);

    /**
     * Returns the zone name of this entity dealer.
     *
     * @return the zone name of this entity dealer
     */
    @AutoEscape
    public String getZoneName();

    /**
     * Sets the zone name of this entity dealer.
     *
     * @param zoneName the zone name of this entity dealer
     */
    public void setZoneName(String zoneName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityDealer entityDealer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityDealer> toCacheModel();

    @Override
    public EntityDealer toEscapedModel();

    @Override
    public EntityDealer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
