package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EntityBrand service. Represents a row in the &quot;Brand&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityBrandModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityBrandImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityBrand
 * @see com.consistent.ucwrt.model.impl.EntityBrandImpl
 * @see com.consistent.ucwrt.model.impl.EntityBrandModelImpl
 * @generated
 */
public interface EntityBrandModel extends BaseModel<EntityBrand> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity brand model instance should use the {@link EntityBrand} interface instead.
     */

    /**
     * Returns the primary key of this entity brand.
     *
     * @return the primary key of this entity brand
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity brand.
     *
     * @param primaryKey the primary key of this entity brand
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the brand ID of this entity brand.
     *
     * @return the brand ID of this entity brand
     */
    public int getBrandId();

    /**
     * Sets the brand ID of this entity brand.
     *
     * @param brandId the brand ID of this entity brand
     */
    public void setBrandId(int brandId);

    /**
     * Returns the brand name of this entity brand.
     *
     * @return the brand name of this entity brand
     */
    @AutoEscape
    public String getBrandName();

    /**
     * Sets the brand name of this entity brand.
     *
     * @param brandName the brand name of this entity brand
     */
    public void setBrandName(String brandName);

    /**
     * Returns the brand description of this entity brand.
     *
     * @return the brand description of this entity brand
     */
    @AutoEscape
    public String getBrandDescription();

    /**
     * Sets the brand description of this entity brand.
     *
     * @param brandDescription the brand description of this entity brand
     */
    public void setBrandDescription(String brandDescription);

    /**
     * Returns the brand registration date of this entity brand.
     *
     * @return the brand registration date of this entity brand
     */
    public Date getBrandRegistrationDate();

    /**
     * Sets the brand registration date of this entity brand.
     *
     * @param brandRegistrationDate the brand registration date of this entity brand
     */
    public void setBrandRegistrationDate(Date brandRegistrationDate);

    /**
     * Returns the register data of this entity brand.
     *
     * @return the register data of this entity brand
     */
    @AutoEscape
    public String getRegisterData();

    /**
     * Sets the register data of this entity brand.
     *
     * @param registerData the register data of this entity brand
     */
    public void setRegisterData(String registerData);

    /**
     * Returns the responsible user of this entity brand.
     *
     * @return the responsible user of this entity brand
     */
    @AutoEscape
    public String getResponsibleUser();

    /**
     * Sets the responsible user of this entity brand.
     *
     * @param responsibleUser the responsible user of this entity brand
     */
    public void setResponsibleUser(String responsibleUser);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityBrand entityBrand);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityBrand> toCacheModel();

    @Override
    public EntityBrand toEscapedModel();

    @Override
    public EntityBrand toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
