package com.consistent.ucwrt.model;

import com.consistent.ucwrt.service.persistence.EntityModelPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EntityModel service. Represents a row in the &quot;Model&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityModelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityModelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityModel
 * @see com.consistent.ucwrt.model.impl.EntityModelImpl
 * @see com.consistent.ucwrt.model.impl.EntityModelModelImpl
 * @generated
 */
public interface EntityModelModel extends BaseModel<EntityModel> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity model model instance should use the {@link EntityModel} interface instead.
     */

    /**
     * Returns the primary key of this entity model.
     *
     * @return the primary key of this entity model
     */
    public EntityModelPK getPrimaryKey();

    /**
     * Sets the primary key of this entity model.
     *
     * @param primaryKey the primary key of this entity model
     */
    public void setPrimaryKey(EntityModelPK primaryKey);

    /**
     * Returns the model ID of this entity model.
     *
     * @return the model ID of this entity model
     */
    public int getModelId();

    /**
     * Sets the model ID of this entity model.
     *
     * @param modelId the model ID of this entity model
     */
    public void setModelId(int modelId);

    /**
     * Returns the brand ID of this entity model.
     *
     * @return the brand ID of this entity model
     */
    public int getBrandId();

    /**
     * Sets the brand ID of this entity model.
     *
     * @param brandId the brand ID of this entity model
     */
    public void setBrandId(int brandId);

    /**
     * Returns the year model of this entity model.
     *
     * @return the year model of this entity model
     */
    public int getYearModel();

    /**
     * Sets the year model of this entity model.
     *
     * @param yearModel the year model of this entity model
     */
    public void setYearModel(int yearModel);

    /**
     * Returns the model name of this entity model.
     *
     * @return the model name of this entity model
     */
    @AutoEscape
    public String getModelName();

    /**
     * Sets the model name of this entity model.
     *
     * @param modelName the model name of this entity model
     */
    public void setModelName(String modelName);

    /**
     * Returns the model description of this entity model.
     *
     * @return the model description of this entity model
     */
    @AutoEscape
    public String getModelDescription();

    /**
     * Sets the model description of this entity model.
     *
     * @param modelDescription the model description of this entity model
     */
    public void setModelDescription(String modelDescription);

    /**
     * Returns the model registration date of this entity model.
     *
     * @return the model registration date of this entity model
     */
    public Date getModelRegistrationDate();

    /**
     * Sets the model registration date of this entity model.
     *
     * @param modelRegistrationDate the model registration date of this entity model
     */
    public void setModelRegistrationDate(Date modelRegistrationDate);

    /**
     * Returns the model register data of this entity model.
     *
     * @return the model register data of this entity model
     */
    @AutoEscape
    public String getModelRegisterData();

    /**
     * Sets the model register data of this entity model.
     *
     * @param modelRegisterData the model register data of this entity model
     */
    public void setModelRegisterData(String modelRegisterData);

    /**
     * Returns the model responsible user of this entity model.
     *
     * @return the model responsible user of this entity model
     */
    @AutoEscape
    public String getModelResponsibleUser();

    /**
     * Sets the model responsible user of this entity model.
     *
     * @param modelResponsibleUser the model responsible user of this entity model
     */
    public void setModelResponsibleUser(String modelResponsibleUser);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityModel entityModel);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityModel> toCacheModel();

    @Override
    public EntityModel toEscapedModel();

    @Override
    public EntityModel toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
