package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityGParameter service. Represents a row in the &quot;GParameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityGParameterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityGParameterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityGParameter
 * @see com.consistent.ucwrt.model.impl.EntityGParameterImpl
 * @see com.consistent.ucwrt.model.impl.EntityGParameterModelImpl
 * @generated
 */
public interface EntityGParameterModel extends BaseModel<EntityGParameter> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity g parameter model instance should use the {@link EntityGParameter} interface instead.
     */

    /**
     * Returns the primary key of this entity g parameter.
     *
     * @return the primary key of this entity g parameter
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this entity g parameter.
     *
     * @param primaryKey the primary key of this entity g parameter
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the parameter name of this entity g parameter.
     *
     * @return the parameter name of this entity g parameter
     */
    @AutoEscape
    public String getParameterName();

    /**
     * Sets the parameter name of this entity g parameter.
     *
     * @param parameterName the parameter name of this entity g parameter
     */
    public void setParameterName(String parameterName);

    /**
     * Returns the value of this entity g parameter.
     *
     * @return the value of this entity g parameter
     */
    @AutoEscape
    public String getValue();

    /**
     * Sets the value of this entity g parameter.
     *
     * @param value the value of this entity g parameter
     */
    public void setValue(String value);

    /**
     * Returns the description of this entity g parameter.
     *
     * @return the description of this entity g parameter
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this entity g parameter.
     *
     * @param description the description of this entity g parameter
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityGParameter entityGParameter);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityGParameter> toCacheModel();

    @Override
    public EntityGParameter toEscapedModel();

    @Override
    public EntityGParameter toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
