package com.consistent.ucwrt.model;

import com.consistent.ucwrt.service.persistence.EntityEmploymentPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityEmployment service. Represents a row in the &quot;Employment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityEmploymentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityEmploymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityEmployment
 * @see com.consistent.ucwrt.model.impl.EntityEmploymentImpl
 * @see com.consistent.ucwrt.model.impl.EntityEmploymentModelImpl
 * @generated
 */
public interface EntityEmploymentModel extends BaseModel<EntityEmployment> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity employment model instance should use the {@link EntityEmployment} interface instead.
     */

    /**
     * Returns the primary key of this entity employment.
     *
     * @return the primary key of this entity employment
     */
    public EntityEmploymentPK getPrimaryKey();

    /**
     * Sets the primary key of this entity employment.
     *
     * @param primaryKey the primary key of this entity employment
     */
    public void setPrimaryKey(EntityEmploymentPK primaryKey);

    /**
     * Returns the employment ID of this entity employment.
     *
     * @return the employment ID of this entity employment
     */
    @AutoEscape
    public String getEmploymentId();

    /**
     * Sets the employment ID of this entity employment.
     *
     * @param employmentId the employment ID of this entity employment
     */
    public void setEmploymentId(String employmentId);

    /**
     * Returns the employment name of this entity employment.
     *
     * @return the employment name of this entity employment
     */
    @AutoEscape
    public String getEmploymentName();

    /**
     * Sets the employment name of this entity employment.
     *
     * @param employmentName the employment name of this entity employment
     */
    public void setEmploymentName(String employmentName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityEmployment entityEmployment);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityEmployment> toCacheModel();

    @Override
    public EntityEmployment toEscapedModel();

    @Override
    public EntityEmployment toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
