package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EntityCustomer service. Represents a row in the &quot;Customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityCustomerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityCustomerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityCustomer
 * @see com.consistent.ucwrt.model.impl.EntityCustomerImpl
 * @see com.consistent.ucwrt.model.impl.EntityCustomerModelImpl
 * @generated
 */
public interface EntityCustomerModel extends BaseModel<EntityCustomer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity customer model instance should use the {@link EntityCustomer} interface instead.
     */

    /**
     * Returns the primary key of this entity customer.
     *
     * @return the primary key of this entity customer
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity customer.
     *
     * @param primaryKey the primary key of this entity customer
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the client ID of this entity customer.
     *
     * @return the client ID of this entity customer
     */
    public int getClientId();

    /**
     * Sets the client ID of this entity customer.
     *
     * @param clientId the client ID of this entity customer
     */
    public void setClientId(int clientId);

    /**
     * Returns the first name of this entity customer.
     *
     * @return the first name of this entity customer
     */
    @AutoEscape
    public String getFirstName();

    /**
     * Sets the first name of this entity customer.
     *
     * @param firstName the first name of this entity customer
     */
    public void setFirstName(String firstName);

    /**
     * Returns the last name of this entity customer.
     *
     * @return the last name of this entity customer
     */
    @AutoEscape
    public String getLastName();

    /**
     * Sets the last name of this entity customer.
     *
     * @param lastName the last name of this entity customer
     */
    public void setLastName(String lastName);

    /**
     * Returns the second last name of this entity customer.
     *
     * @return the second last name of this entity customer
     */
    @AutoEscape
    public String getSecondLastName();

    /**
     * Sets the second last name of this entity customer.
     *
     * @param secondLastName the second last name of this entity customer
     */
    public void setSecondLastName(String secondLastName);

    /**
     * Returns the email of this entity customer.
     *
     * @return the email of this entity customer
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this entity customer.
     *
     * @param email the email of this entity customer
     */
    public void setEmail(String email);

    /**
     * Returns the rfc of this entity customer.
     *
     * @return the rfc of this entity customer
     */
    @AutoEscape
    public String getRfc();

    /**
     * Sets the rfc of this entity customer.
     *
     * @param rfc the rfc of this entity customer
     */
    public void setRfc(String rfc);

    /**
     * Returns the cell phone of this entity customer.
     *
     * @return the cell phone of this entity customer
     */
    @AutoEscape
    public String getCellPhone();

    /**
     * Sets the cell phone of this entity customer.
     *
     * @param cellPhone the cell phone of this entity customer
     */
    public void setCellPhone(String cellPhone);

    /**
     * Returns the legal personality of this entity customer.
     *
     * @return the legal personality of this entity customer
     */
    @AutoEscape
    public String getLegalPersonality();

    /**
     * Sets the legal personality of this entity customer.
     *
     * @param legalPersonality the legal personality of this entity customer
     */
    public void setLegalPersonality(String legalPersonality);

    /**
     * Returns the person type of this entity customer.
     *
     * @return the person type of this entity customer
     */
    @AutoEscape
    public String getPersonType();

    /**
     * Sets the person type of this entity customer.
     *
     * @param personType the person type of this entity customer
     */
    public void setPersonType(String personType);

    /**
     * Returns the phone of this entity customer.
     *
     * @return the phone of this entity customer
     */
    @AutoEscape
    public String getPhone();

    /**
     * Sets the phone of this entity customer.
     *
     * @param phone the phone of this entity customer
     */
    public void setPhone(String phone);

    /**
     * Returns the registration date of this entity customer.
     *
     * @return the registration date of this entity customer
     */
    public Date getRegistrationDate();

    /**
     * Sets the registration date of this entity customer.
     *
     * @param registrationDate the registration date of this entity customer
     */
    public void setRegistrationDate(Date registrationDate);

    /**
     * Returns the comments of this entity customer.
     *
     * @return the comments of this entity customer
     */
    @AutoEscape
    public String getComments();

    /**
     * Sets the comments of this entity customer.
     *
     * @param comments the comments of this entity customer
     */
    public void setComments(String comments);

    /**
     * Returns the dealer ID of this entity customer.
     *
     * @return the dealer ID of this entity customer
     */
    @AutoEscape
    public String getDealerId();

    /**
     * Sets the dealer ID of this entity customer.
     *
     * @param dealerId the dealer ID of this entity customer
     */
    public void setDealerId(String dealerId);

    /**
     * Returns the business brand name of this entity customer.
     *
     * @return the business brand name of this entity customer
     */
    @AutoEscape
    public String getBusinessBrandName();

    /**
     * Sets the business brand name of this entity customer.
     *
     * @param businessBrandName the business brand name of this entity customer
     */
    public void setBusinessBrandName(String businessBrandName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityCustomer entityCustomer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityCustomer> toCacheModel();

    @Override
    public EntityCustomer toEscapedModel();

    @Override
    public EntityCustomer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
