package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityZone service. Represents a row in the &quot;Zone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityZoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityZoneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityZone
 * @see com.consistent.ucwrt.model.impl.EntityZoneImpl
 * @see com.consistent.ucwrt.model.impl.EntityZoneModelImpl
 * @generated
 */
public interface EntityZoneModel extends BaseModel<EntityZone> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity zone model instance should use the {@link EntityZone} interface instead.
     */

    /**
     * Returns the primary key of this entity zone.
     *
     * @return the primary key of this entity zone
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this entity zone.
     *
     * @param primaryKey the primary key of this entity zone
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the zone name of this entity zone.
     *
     * @return the zone name of this entity zone
     */
    @AutoEscape
    public String getZoneName();

    /**
     * Sets the zone name of this entity zone.
     *
     * @param zoneName the zone name of this entity zone
     */
    public void setZoneName(String zoneName);

    /**
     * Returns the description zone of this entity zone.
     *
     * @return the description zone of this entity zone
     */
    @AutoEscape
    public String getDescriptionZone();

    /**
     * Sets the description zone of this entity zone.
     *
     * @param descriptionZone the description zone of this entity zone
     */
    public void setDescriptionZone(String descriptionZone);

    /**
     * Returns the user zone manager of this entity zone.
     *
     * @return the user zone manager of this entity zone
     */
    @AutoEscape
    public String getUserZoneManager();

    /**
     * Sets the user zone manager of this entity zone.
     *
     * @param userZoneManager the user zone manager of this entity zone
     */
    public void setUserZoneManager(String userZoneManager);

    /**
     * Returns the user sales area manager of this entity zone.
     *
     * @return the user sales area manager of this entity zone
     */
    @AutoEscape
    public String getUserSalesAreaManager();

    /**
     * Sets the user sales area manager of this entity zone.
     *
     * @param userSalesAreaManager the user sales area manager of this entity zone
     */
    public void setUserSalesAreaManager(String userSalesAreaManager);

    /**
     * Returns the user regional area manager of this entity zone.
     *
     * @return the user regional area manager of this entity zone
     */
    @AutoEscape
    public String getUserRegionalAreaManager();

    /**
     * Sets the user regional area manager of this entity zone.
     *
     * @param userRegionalAreaManager the user regional area manager of this entity zone
     */
    public void setUserRegionalAreaManager(String userRegionalAreaManager);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityZone entityZone);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityZone> toCacheModel();

    @Override
    public EntityZone toEscapedModel();

    @Override
    public EntityZone toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
