package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntityEvent service. Represents a row in the &quot;Event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntityEventModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntityEventImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityEvent
 * @see com.consistent.ucwrt.model.impl.EntityEventImpl
 * @see com.consistent.ucwrt.model.impl.EntityEventModelImpl
 * @generated
 */
public interface EntityEventModel extends BaseModel<EntityEvent> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity event model instance should use the {@link EntityEvent} interface instead.
     */

    /**
     * Returns the primary key of this entity event.
     *
     * @return the primary key of this entity event
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity event.
     *
     * @param primaryKey the primary key of this entity event
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the event ID of this entity event.
     *
     * @return the event ID of this entity event
     */
    public int getEventId();

    /**
     * Sets the event ID of this entity event.
     *
     * @param eventId the event ID of this entity event
     */
    public void setEventId(int eventId);

    /**
     * Returns the event name of this entity event.
     *
     * @return the event name of this entity event
     */
    @AutoEscape
    public String getEventName();

    /**
     * Sets the event name of this entity event.
     *
     * @param eventName the event name of this entity event
     */
    public void setEventName(String eventName);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntityEvent entityEvent);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntityEvent> toCacheModel();

    @Override
    public EntityEvent toEscapedModel();

    @Override
    public EntityEvent toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
