package com.consistent.ucwrt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EntitySourceOfSupply service. Represents a row in the &quot;SourceOfSupply&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.consistent.ucwrt.model.impl.EntitySourceOfSupplyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.consistent.ucwrt.model.impl.EntitySourceOfSupplyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntitySourceOfSupply
 * @see com.consistent.ucwrt.model.impl.EntitySourceOfSupplyImpl
 * @see com.consistent.ucwrt.model.impl.EntitySourceOfSupplyModelImpl
 * @generated
 */
public interface EntitySourceOfSupplyModel extends BaseModel<EntitySourceOfSupply> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a entity source of supply model instance should use the {@link EntitySourceOfSupply} interface instead.
     */

    /**
     * Returns the primary key of this entity source of supply.
     *
     * @return the primary key of this entity source of supply
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this entity source of supply.
     *
     * @param primaryKey the primary key of this entity source of supply
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the source supply ID of this entity source of supply.
     *
     * @return the source supply ID of this entity source of supply
     */
    public int getSourceSupplyId();

    /**
     * Sets the source supply ID of this entity source of supply.
     *
     * @param sourceSupplyId the source supply ID of this entity source of supply
     */
    public void setSourceSupplyId(int sourceSupplyId);

    /**
     * Returns the source of supply of this entity source of supply.
     *
     * @return the source of supply of this entity source of supply
     */
    @AutoEscape
    public String getSourceOfSupply();

    /**
     * Sets the source of supply of this entity source of supply.
     *
     * @param sourceOfSupply the source of supply of this entity source of supply
     */
    public void setSourceOfSupply(String sourceOfSupply);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(EntitySourceOfSupply entitySourceOfSupply);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EntitySourceOfSupply> toCacheModel();

    @Override
    public EntitySourceOfSupply toEscapedModel();

    @Override
    public EntitySourceOfSupply toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
